### Notebook for concept detection in neural network

In [1]:
%load_ext autoreload
%autoreload 2

In [29]:
import numpy as np
import os
import sys
from tqdm import tqdm
import json
import random
import string

sys.path.append(os.path.abspath(os.path.join(os.path.pardir, 'src')))

import concepts
import env
from policy import ActorCriticNet

model_name = "net"
session_name = "starship"
board_size = 5
board_name = f'{board_size}x{board_size}'

agents_to_sample = [0, 150, 300, 450, 600, 750, 900, 1050, 1200, 1500, 1800]

full_model_path = f"../models/saved_sessions/board_size_{board_size}/{session_name}/"

CONCEPT_FUNC = concepts.play_center_in_opening

CONCEPT_NAME = concepts.play_center_in_opening.__name__

CASES_TO_SAMPLE = 1000 # 25000


In [30]:
def load_model(full_name, model_name, epoch):
    model_path = full_name + model_name + "_" + str(epoch) + ".keras"
    model = ActorCriticNet(board_size, model_path)
    return model

agents = [load_model(full_model_path, model_name, epoch) for epoch in agents_to_sample]

In [32]:
def play_match(agents: list[ActorCriticNet], board_size, concept_function):
    go_env = env.GoEnv(board_size)
    state = go_env.reset()

    player_to_start = 1 if np.random.random() > 0.5 else 0
    current_player = player_to_start

    total_moves = board_size * board_size * 4
    moves = 0
    random_moves = False

    positive_cases = []
    negative_cases = []

    sample_ratio = 0.2
    alpha = 0.2 # The higher, the more unique games. 0 = argmax, 1 = distribution 

    game_over = False

    while not game_over:
        if moves == total_moves:
            break
        # Remove array index 3 and 5 from the current state making it an shape of (4, 5, 5)
        state_copy = np.delete(state, [3, 5], axis=0)
        
        if np.random.random() < sample_ratio:
            pos = concept_function(state)
            if pos:
                positive_cases.append(state_copy)
            elif not pos:
                negative_cases.append(state_copy)

        if random_moves:
            action = go_env.uniform_random_action()
        else:
            action = agents[current_player].best_action(state, alpha=alpha)

        state, _, game_over, _ = go_env.step(action)
        moves += 1

        current_player = (current_player + 1) % 2
    
    return positive_cases, negative_cases

positive_cases = []
negative_cases = []

positive_bar = tqdm(total=CASES_TO_SAMPLE, desc="Positive cases")

while len(positive_cases) < CASES_TO_SAMPLE or len(negative_cases) < CASES_TO_SAMPLE:
    for i in range(len(agents)):
        for j in range(i + 1, len(agents)):
            pos, neg = play_match([agents[i], agents[j]], board_size, CONCEPT_FUNC)

            positive_cases.extend(pos)
            negative_cases.extend(neg)

            positive_bar.update(len(pos))

positive_cases = positive_cases[:CASES_TO_SAMPLE]
negative_cases = negative_cases[:CASES_TO_SAMPLE]

# Create numpy arrays
positive_cases = np.array(positive_cases)
negative_cases = np.array(negative_cases)

Positive cases:   1%|          | 10/1000 [00:03<03:20,  4.94it/s]

5.0


Positive cases:   2%|▏         | 20/1000 [00:05<03:16,  4.98it/s]

7.0
8.0


Positive cases:   2%|▏         | 23/1000 [00:05<02:41,  6.05it/s]

5.0


Positive cases:   6%|▌         | 59/1000 [00:17<02:55,  5.37it/s]

5.0
6.0


Positive cases:   6%|▋         | 65/1000 [00:19<05:50,  2.67it/s]

5.0


Positive cases:   7%|▋         | 69/1000 [00:21<06:36,  2.35it/s]

6.0


Positive cases:   8%|▊         | 77/1000 [00:23<03:24,  4.52it/s]

5.0


Positive cases:   9%|▉         | 92/1000 [00:27<02:27,  6.15it/s]

5.0
6.0
5.0


Positive cases:  11%|█         | 111/1000 [00:34<04:54,  3.02it/s]

6.0
5.0
6.0


Positive cases:  12%|█▏        | 117/1000 [00:34<02:03,  7.14it/s]

5.0


Positive cases:  12%|█▏        | 120/1000 [00:36<03:42,  3.95it/s]

5.0


Positive cases:  13%|█▎        | 131/1000 [00:41<03:43,  3.89it/s]

5.0


Positive cases:  13%|█▎        | 133/1000 [00:42<04:55,  2.94it/s]

5.0


Positive cases:  14%|█▍        | 145/1000 [00:45<02:35,  5.50it/s]

6.0


Positive cases:  16%|█▌        | 159/1000 [00:50<06:04,  2.31it/s]

5.0


Positive cases:  17%|█▋        | 173/1000 [00:55<06:29,  2.13it/s]

5.0


Positive cases:  19%|█▉        | 190/1000 [01:02<04:27,  3.03it/s]

6.0


Positive cases:  20%|██        | 204/1000 [01:07<04:00,  3.31it/s]

5.0


Positive cases:  21%|██        | 210/1000 [01:10<03:42,  3.55it/s]

5.0


Positive cases:  22%|██▏       | 216/1000 [01:12<05:38,  2.31it/s]

6.0


Positive cases:  23%|██▎       | 227/1000 [01:18<06:50,  1.88it/s]

5.0


Positive cases:  23%|██▎       | 230/1000 [01:20<06:33,  1.96it/s]

6.0


Positive cases:  23%|██▎       | 231/1000 [01:20<06:25,  1.99it/s]

6.0


Positive cases:  24%|██▎       | 235/1000 [01:21<03:51,  3.31it/s]

5.0


Positive cases:  25%|██▍       | 246/1000 [01:26<04:18,  2.92it/s]

5.0


Positive cases:  27%|██▋       | 271/1000 [01:34<03:49,  3.17it/s]

5.0


Positive cases:  29%|██▉       | 288/1000 [01:40<02:56,  4.04it/s]

5.0


Positive cases:  29%|██▉       | 291/1000 [01:41<02:39,  4.44it/s]

5.0


Positive cases:  32%|███▏      | 316/1000 [01:50<02:19,  4.90it/s]

6.0


Positive cases:  32%|███▏      | 321/1000 [01:51<02:30,  4.50it/s]

5.0


Positive cases:  33%|███▎      | 326/1000 [01:52<02:05,  5.38it/s]

5.0


Positive cases:  33%|███▎      | 332/1000 [01:53<01:24,  7.88it/s]

5.0


Positive cases:  34%|███▍      | 341/1000 [01:57<04:43,  2.33it/s]

5.0


Positive cases:  35%|███▌      | 351/1000 [01:59<02:08,  5.07it/s]

6.0


Positive cases:  38%|███▊      | 382/1000 [02:08<02:00,  5.12it/s]

5.0
8.0


Positive cases:  39%|███▉      | 391/1000 [02:13<04:23,  2.31it/s]

5.0


Positive cases:  40%|███▉      | 395/1000 [02:16<06:49,  1.48it/s]

5.0
5.0


Positive cases:  40%|████      | 403/1000 [02:19<03:31,  2.82it/s]

5.0


Positive cases:  41%|████      | 406/1000 [02:20<03:44,  2.65it/s]

5.0


Positive cases:  41%|████      | 409/1000 [02:20<01:51,  5.31it/s]

5.0
6.0


Positive cases:  42%|████▏     | 415/1000 [02:21<01:14,  7.90it/s]

6.0


Positive cases:  42%|████▎     | 425/1000 [02:24<02:50,  3.36it/s]

5.0


Positive cases:  44%|████▍     | 441/1000 [02:28<02:34,  3.61it/s]

5.0


Positive cases:  45%|████▍     | 448/1000 [02:30<02:25,  3.80it/s]

6.0


Positive cases:  46%|████▌     | 457/1000 [02:35<03:40,  2.46it/s]

5.0


Positive cases:  46%|████▌     | 461/1000 [02:36<02:16,  3.95it/s]

5.0


Positive cases:  48%|████▊     | 484/1000 [02:39<01:01,  8.36it/s]

6.0


Positive cases:  49%|████▉     | 490/1000 [02:41<01:28,  5.76it/s]

6.0


Positive cases:  50%|████▉     | 497/1000 [02:43<01:59,  4.22it/s]

6.0


Positive cases:  50%|█████     | 500/1000 [02:43<01:44,  4.81it/s]

5.0


Positive cases:  52%|█████▏    | 524/1000 [02:50<02:07,  3.72it/s]

5.0


Positive cases:  54%|█████▍    | 539/1000 [02:54<01:05,  6.99it/s]

7.0


Positive cases:  54%|█████▍    | 542/1000 [02:54<01:04,  7.10it/s]

5.0


Positive cases:  55%|█████▍    | 548/1000 [02:56<02:09,  3.49it/s]

5.0
6.0


Positive cases:  56%|█████▌    | 556/1000 [02:59<02:16,  3.26it/s]

5.0


Positive cases:  56%|█████▋    | 565/1000 [03:04<03:21,  2.16it/s]

6.0


Positive cases:  57%|█████▋    | 574/1000 [03:07<01:21,  5.22it/s]

5.0
6.0
7.0


Positive cases:  60%|█████▉    | 595/1000 [03:13<01:28,  4.57it/s]

5.0


Positive cases:  61%|██████    | 610/1000 [03:16<01:11,  5.44it/s]

5.0


Positive cases:  61%|██████▏   | 613/1000 [03:16<01:03,  6.08it/s]

5.0
8.0


Positive cases:  62%|██████▏   | 616/1000 [03:18<01:37,  3.94it/s]

5.0


Positive cases:  62%|██████▏   | 619/1000 [03:18<01:16,  5.00it/s]

5.0


Positive cases:  64%|██████▍   | 639/1000 [03:27<02:31,  2.39it/s]

7.0


Positive cases:  66%|██████▌   | 658/1000 [03:32<00:53,  6.39it/s]

5.0


Positive cases:  66%|██████▋   | 664/1000 [03:34<01:04,  5.18it/s]

6.0


Positive cases:  67%|██████▋   | 667/1000 [03:34<01:07,  4.95it/s]

6.0
7.0


Positive cases:  68%|██████▊   | 678/1000 [03:37<01:00,  5.30it/s]

5.0
6.0


Positive cases:  68%|██████▊   | 685/1000 [03:40<02:25,  2.16it/s]

8.0


Positive cases:  70%|██████▉   | 696/1000 [03:44<01:36,  3.15it/s]

5.0


Positive cases:  71%|███████   | 712/1000 [03:50<01:08,  4.22it/s]

5.0


Positive cases:  72%|███████▏  | 717/1000 [03:51<01:06,  4.23it/s]

5.0


Positive cases:  72%|███████▏  | 722/1000 [03:52<01:32,  3.00it/s]

5.0
7.0


Positive cases:  75%|███████▍  | 746/1000 [04:01<01:13,  3.48it/s]

5.0


Positive cases:  78%|███████▊  | 782/1000 [04:11<00:30,  7.18it/s]

7.0
5.0


Positive cases:  79%|███████▉  | 791/1000 [04:14<00:57,  3.66it/s]

6.0


Positive cases:  80%|████████  | 803/1000 [04:21<02:37,  1.25it/s]

5.0
6.0


Positive cases:  81%|████████  | 806/1000 [04:22<01:30,  2.15it/s]

7.0


Positive cases:  81%|████████  | 809/1000 [04:22<00:55,  3.45it/s]

5.0
6.0


Positive cases:  82%|████████▏ | 819/1000 [04:26<00:52,  3.45it/s]

5.0


Positive cases:  82%|████████▏ | 821/1000 [04:26<00:38,  4.61it/s]

5.0


Positive cases:  83%|████████▎ | 826/1000 [04:32<03:03,  1.06s/it]

5.0


Positive cases:  83%|████████▎ | 830/1000 [04:33<01:20,  2.11it/s]

5.0


Positive cases:  85%|████████▌ | 850/1000 [04:42<01:39,  1.51it/s]

9.0


Positive cases:  86%|████████▌ | 862/1000 [04:48<00:42,  3.28it/s]

5.0


Positive cases:  87%|████████▋ | 872/1000 [04:52<01:02,  2.06it/s]

5.0


Positive cases:  88%|████████▊ | 878/1000 [04:55<00:48,  2.52it/s]

6.0
8.0


Positive cases:  90%|████████▉ | 895/1000 [05:01<00:25,  4.16it/s]

5.0


Positive cases:  90%|█████████ | 902/1000 [05:04<00:37,  2.63it/s]

5.0


Positive cases:  91%|█████████ | 906/1000 [05:06<00:32,  2.93it/s]

7.0


Positive cases:  92%|█████████▏| 919/1000 [05:09<00:11,  6.77it/s]

5.0


Positive cases:  94%|█████████▍| 938/1000 [05:17<00:32,  1.88it/s]

5.0


Positive cases:  94%|█████████▍| 943/1000 [05:18<00:17,  3.23it/s]

5.0


Positive cases:  94%|█████████▍| 944/1000 [05:18<00:17,  3.27it/s]

5.0


Positive cases:  94%|█████████▍| 945/1000 [05:19<00:18,  2.99it/s]

6.0


Positive cases:  95%|█████████▌| 952/1000 [05:21<00:11,  4.01it/s]

6.0


Positive cases:  96%|█████████▌| 958/1000 [05:24<00:15,  2.65it/s]

5.0
6.0


Positive cases:  96%|█████████▌| 959/1000 [05:25<00:21,  1.91it/s]

5.0


Positive cases:  96%|█████████▌| 961/1000 [05:25<00:14,  2.61it/s]

5.0


Positive cases:  96%|█████████▋| 963/1000 [05:26<00:14,  2.54it/s]

6.0


Positive cases:  97%|█████████▋| 969/1000 [05:26<00:06,  4.77it/s]

5.0


Positive cases:  98%|█████████▊| 976/1000 [05:28<00:04,  5.43it/s]

5.0
6.0


Positive cases:  98%|█████████▊| 982/1000 [05:29<00:04,  4.37it/s]

6.0


Positive cases:  98%|█████████▊| 984/1000 [05:29<00:04,  3.83it/s]

5.0


Positive cases:  99%|█████████▉| 991/1000 [05:33<00:03,  2.48it/s]

6.0


Positive cases: 1007it [05:37,  4.46it/s]                          

5.0


Positive cases: 1012it [05:39,  3.32it/s]

6.0
5.0


Positive cases: 1014it [05:39,  4.38it/s]

In [33]:
# Print shapes
print("Positive cases: ", positive_cases.shape)
print("Negative cases: ", negative_cases.shape)

Positive cases:  (1000, 4, 5, 5)
Negative cases:  (1000, 4, 5, 5)


In [5]:
# Test if there are any duplicates accross the two sets
for i in range(len(positive_cases)):
    for j in range(len(negative_cases)):
        if np.array_equal(positive_cases[i], negative_cases[j]):
            print("Duplicate found!")
            print(positive_cases[i])
            print(negative_cases[j])
            break

In [34]:
# Find the number of any duplicates within the positive cases
duplicate_count = 0
for i in range(len(positive_cases)):
    for j in range(i + 1, len(positive_cases)):
        if np.array_equal(positive_cases[i], positive_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in positive cases: ", duplicate_count)

# Find the number of any duplicates within the negative cases
duplicate_count = 0
for i in range(len(negative_cases)):
    for j in range(i + 1, len(negative_cases)):
        if np.array_equal(negative_cases[i], negative_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in negative: ", duplicate_count)

Duplicate count in positive cases:  736
Duplicate count in negative:  38


In [35]:
# Print all the positive cases
for i in range(len(positive_cases)):
    print(f"Positive case {i}:")
    print(positive_cases[i])
    print()

Positive case 0:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

Positive case 1:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

Positive case 2:
[[[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.

In [36]:
# Positions to consider are 80% of the total positions
POSITIONS_TO_CONSIDER = int(0.8 * positive_cases.shape[0] * 2)
print(f"Positions to consider: {POSITIONS_TO_CONSIDER}")
#POSITIONS_TO_CONSIDER = 4000 #40000
VALIDATION_POSITIONS = 10000 #10000

BINARY = True

Positions to consider: 1600


In [37]:
# First test if the concept can be regressed form the inputs
name = "input"
all_cases = np.concatenate([positive_cases, negative_cases])
all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
all_labels = np.array(all_labels)
shuffled_indices = np.arange(all_labels.shape[0])

np.random.shuffle(shuffled_indices)

all_cases = all_cases[shuffled_indices]
all_labels = all_labels[shuffled_indices]

points = all_cases.reshape(all_cases.shape[0], -1)

# Use the regression
score = concepts.perform_regression(
    points=points[:POSITIONS_TO_CONSIDER], 
    targets=all_labels[:POSITIONS_TO_CONSIDER], 
    validation_points=points[POSITIONS_TO_CONSIDER:], 
    validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
    is_binary=BINARY
)

print("Regression score: ", score)

# Remove the files if they exist
if os.path.exists("../concept_presences/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
    # Test if epoch folder exists
    if os.path.exists("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
        # Remove all files in the epoch folder
        # Fist save the 
        for file in os.listdir("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
            os.remove("../concept_presences/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name, file))

os.makedirs("../concept_presences", exist_ok=True)
os.makedirs("../concept_presences/{}".format(board_name), exist_ok=True)
os.makedirs("../concept_presences/{}/{}".format(board_name, session_name), exist_ok=True)
os.makedirs("../concept_presences/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
os.makedirs("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name), exist_ok=True)

random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

# Save concept presences in json file
with open("../concept_presences/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, name, random_suffix), "w") as f:
    json.dump(score, f)

Epoch 1/50


50/50 [==============================] - 1s 5ms/step - loss: 0.8897 - val_loss: 0.8613
Epoch 2/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8666 - val_loss: 0.8429
Epoch 3/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8459 - val_loss: 0.8270
Epoch 4/50
50/50 [==============================] - 0s 3ms/step - loss: 0.8278 - val_loss: 0.8128
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8115 - val_loss: 0.7992
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7964 - val_loss: 0.7870
Epoch 7/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7825 - val_loss: 0.7757
Epoch 8/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7696 - val_loss: 0.7650
Epoch 9/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7576 - val_loss: 0.7548
Epoch 10/50
50/50 [==============================] - 0s 3ms/step - loss: 0.7463 - val_loss: 0.7455
Epoch 11/50
50/50 [===========

In [38]:
epochs_to_look_at = [0, 150, 300, 450, 600, 750, 900, 1050, 1200, 1500, 1800]

for epoch in epochs_to_look_at:
    path = full_model_path + model_name + "_" + str(epoch) + ".keras"
    model = ActorCriticNet(board_size, path)

    # Will have a length equal to the sum of the numer of rows in the positive and negative cases arrays
    # And will contain 1s for positive cases and 0s for negative cases
    # Is used as labels/targets for the regression
    all_cases = np.concatenate([positive_cases, negative_cases])
    all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
    all_labels = np.array(all_labels)
    shuffled_indices = np.arange(all_labels.shape[0])

    np.random.shuffle(shuffled_indices)

    all_cases = all_cases[shuffled_indices]
    all_labels = all_labels[shuffled_indices]

    concept_presences = {}
    
    outputs = model.get_all_activation_values(all_cases)

    # Merge outputs
    merged_outputs = []
    for output_batch in outputs:
        for i, output_layer in enumerate(output_batch):
            if len(merged_outputs) <= i:
                merged_outputs.append([])
            merged_outputs[i].extend(output_layer)

    for i, layer_output in enumerate(merged_outputs):
        merged_outputs[i] = np.array(merged_outputs[i])
    
    outputs = merged_outputs

    # Perform regression
    concept_presence_per_layer = []
    for (i, output) in enumerate(outputs):
        points = output.reshape((output.shape[0], np.prod(output.shape[1:])))
        # So one has (n, k) samples where n is the number of positions, and k is the total number of activation values in layer i.
        print(f"Performing regression for layer {i}")
        score = concepts.perform_regression(
            points=points[:POSITIONS_TO_CONSIDER], 
            targets=all_labels[:POSITIONS_TO_CONSIDER], 
            validation_points=points[POSITIONS_TO_CONSIDER:], 
            validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
            is_binary=BINARY
        )
        concept_presence_per_layer.append(score)

        print(f"The presence of {CONCEPT_NAME} in resblock {i} is {score}")
    concept_presences[CONCEPT_NAME] = concept_presence_per_layer

    # Remove the files if they exist
    if os.path.exists("../concept_presences/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
        # Test if epoch folder exists
        if os.path.exists("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
            # Remove all files in the epoch folder
            # Fist save the 
            for file in os.listdir("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
                os.remove("../concept_presences/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch, file))

    os.makedirs("../concept_presences", exist_ok=True)
    os.makedirs("../concept_presences/{}".format(board_name), exist_ok=True)
    os.makedirs("../concept_presences/{}/{}".format(board_name, session_name), exist_ok=True)
    os.makedirs("../concept_presences/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
    os.makedirs("../concept_presences/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch), exist_ok=True)

    random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

    # Save concept presences in json file
    with open("../concept_presences/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, epoch, random_suffix), "w") as f:
        json.dump(concept_presences[CONCEPT_NAME], f)


Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 224.06it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 1s 8ms/step - loss: 0.9664 - val_loss: 0.9531
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9408 - val_loss: 0.9275
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9169 - val_loss: 0.9037
Epoch 4/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8944 - val_loss: 0.8811
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8729 - val_loss: 0.8596
Epoch 6/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8525 - val_loss: 0.8396
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8333 - val_loss: 0.8205
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8153 - val_loss: 0.8027
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7984 - val_loss: 0.7863
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7824 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 287.96it/s]

Performing regression for layer 0
Epoch 1/50


50/50 [==============================] - 0s 3ms/step - loss: 1.1247 - val_loss: 0.9998
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9755 - val_loss: 0.9131
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9004 - val_loss: 0.8657
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8546 - val_loss: 0.8315
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8201 - val_loss: 0.8038
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7914 - val_loss: 0.7796
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7665 - val_loss: 0.7579
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7443 - val_loss: 0.7387
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7241 - val_loss: 0.7206
Epoch 10/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7059 - val_loss: 0.7043
Epoch 11/50
50/50 [===========

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 291.36it/s]

Performing regression for layer 0
Epoch 1/50


50/50 [==============================] - 0s 3ms/step - loss: 1.0159 - val_loss: 0.9552
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9345 - val_loss: 0.8950
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8782 - val_loss: 0.8489
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8325 - val_loss: 0.8111
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7949 - val_loss: 0.7795
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7634 - val_loss: 0.7524
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7365 - val_loss: 0.7287
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7124 - val_loss: 0.7073
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6909 - val_loss: 0.6879
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6713 - val_loss: 0.6701
Epoch 11/50
50/50 [===========

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 228.13it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 0s 3ms/step - loss: 0.9193 - val_loss: 0.8946
Epoch 2/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8652 - val_loss: 0.8461
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8208 - val_loss: 0.8032
Epoch 4/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7830 - val_loss: 0.7682
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7500 - val_loss: 0.7383
Epoch 6/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7213 - val_loss: 0.7111
Epoch 7/50
50/50 [==============================] - 0s 2ms/step - loss: 0.6958 - val_loss: 0.6877
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6733 - val_loss: 0.6675
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6531 - val_loss: 0.6493
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6349 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 277.92it/s]

Performing regression for layer 0
Epoch 1/50


50/50 [==============================] - 0s 3ms/step - loss: 0.9417 - val_loss: 0.9112
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8864 - val_loss: 0.8608
Epoch 3/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8400 - val_loss: 0.8195
Epoch 4/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8004 - val_loss: 0.7842
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7660 - val_loss: 0.7537
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7363 - val_loss: 0.7270
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7098 - val_loss: 0.7033
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6866 - val_loss: 0.6825
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6655 - val_loss: 0.6639
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6468 - val_loss: 0.6466
Epoch 11/50
50/50 [===========

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 228.72it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 0s 3ms/step - loss: 0.9624 - val_loss: 0.9297
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8966 - val_loss: 0.8708
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8469 - val_loss: 0.8220
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8050 - val_loss: 0.7809
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7697 - val_loss: 0.7453
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7390 - val_loss: 0.7144
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7120 - val_loss: 0.6872
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6884 - val_loss: 0.6630
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6675 - val_loss: 0.6422
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6489 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 228.55it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 0s 3ms/step - loss: 0.9592 - val_loss: 0.9330
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9075 - val_loss: 0.8904
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8635 - val_loss: 0.8534
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8254 - val_loss: 0.8200
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7921 - val_loss: 0.7905
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7628 - val_loss: 0.7653
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7370 - val_loss: 0.7421
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7142 - val_loss: 0.7219
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6933 - val_loss: 0.7033
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6746 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 261.18it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 0s 3ms/step - loss: 1.0871 - val_loss: 1.0285
Epoch 2/50
50/50 [==============================] - 0s 2ms/step - loss: 1.0103 - val_loss: 0.9655
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9450 - val_loss: 0.9120
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8902 - val_loss: 0.8666
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8439 - val_loss: 0.8273
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8043 - val_loss: 0.7945
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7705 - val_loss: 0.7655
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7409 - val_loss: 0.7410
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7155 - val_loss: 0.7187
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6931 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 219.15it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 1s 4ms/step - loss: 0.9078 - val_loss: 0.8691
Epoch 2/50
50/50 [==============================] - 0s 2ms/step - loss: 0.8446 - val_loss: 0.8157
Epoch 3/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7957 - val_loss: 0.7729
Epoch 4/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7563 - val_loss: 0.7376
Epoch 5/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7239 - val_loss: 0.7079
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6970 - val_loss: 0.6821
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6736 - val_loss: 0.6604
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6535 - val_loss: 0.6411
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6355 - val_loss: 0.6235
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6189 - va

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 287.94it/s]

Performing regression for layer 0
Epoch 1/50


50/50 [==============================] - 0s 3ms/step - loss: 0.9614 - val_loss: 0.9265
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8740 - val_loss: 0.8620
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8141 - val_loss: 0.8126
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7675 - val_loss: 0.7731
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7301 - val_loss: 0.7415
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6997 - val_loss: 0.7159
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6746 - val_loss: 0.6935
Epoch 8/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6526 - val_loss: 0.6744
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6339 - val_loss: 0.6577
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6170 - val_loss: 0.6428
Epoch 11/50
50/50 [===========

Getting activation outputs: 100%|██████████| 63/63 [00:00<00:00, 198.34it/s]


Performing regression for layer 0
Epoch 1/50
50/50 [==============================] - 0s 3ms/step - loss: 1.0878 - val_loss: 1.0189
Epoch 2/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9798 - val_loss: 0.9274
Epoch 3/50
50/50 [==============================] - 0s 1ms/step - loss: 0.9065 - val_loss: 0.8574
Epoch 4/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8487 - val_loss: 0.8020
Epoch 5/50
50/50 [==============================] - 0s 1ms/step - loss: 0.8016 - val_loss: 0.7580
Epoch 6/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7635 - val_loss: 0.7229
Epoch 7/50
50/50 [==============================] - 0s 1ms/step - loss: 0.7318 - val_loss: 0.6940
Epoch 8/50
50/50 [==============================] - 0s 2ms/step - loss: 0.7052 - val_loss: 0.6696
Epoch 9/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6822 - val_loss: 0.6487
Epoch 10/50
50/50 [==============================] - 0s 1ms/step - loss: 0.6619 - va