In [1]:
%load_ext autoreload
%autoreload 2

In [29]:
import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.pardir, 'src')))
import tensorflow as tf
from policy import ConvNet
from concepts import DynamicConcepts, linear_regression
import absl.logging
import json
import string
import random
import numpy as np
import os
from env import gogame
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # or any {'0', '1', '2'}

absl.logging.set_verbosity(absl.logging.ERROR)

# Set memory growth
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

session_name = "falcon"
model_name = "net"
board_size = 5
board_name = f'{board_size}x{board_size}'
agents_to_sample = [10, 20, 60, 100, 500, 1000]

# Mcts simulations
simulations = 1000

full_model_path = f"../models/saved_sessions/board_size_{board_size}/{session_name}/"

mcts_model_path = f"../models/best_models/board_size_{board_size}/net_1000.keras"

init_state, concept_type_single = DynamicConcepts.life_and_death(board_size)

dynamic_concept = DynamicConcepts(init_state, simulations, board_size, concept_type_single, mcts_model_path)

CONCEPT_NAME = DynamicConcepts.life_and_death.__name__

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 0. 1. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 1. 1. 1. 0.]
  [0. 0. 1. 1. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpqbm65899/assets


INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpqbm65899/assets
2024-02-09 16:10:25.647541: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpqbm65899
2024-02-09 16:10:25.649916: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2024-02-09 16:10:25.649929: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpqbm65899
2024-02-09 16:10:25.658308: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
2024-02-09 16:10:25.703582: I tensorflow/cc/saved_model/loader.cc:215] Running initialization op on SavedModel bundle at path: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpqbm65899
2024-02-09 16:10:25.720179: I tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 72638 microseconds.


In [31]:
positive_cases = []
negative_cases = []

pos, neg = dynamic_concept.generate_cases()

positive_cases.extend(pos)
negative_cases.extend(neg)

# Create numpy arrays
positive_cases = np.array(positive_cases)
negative_cases = np.array(negative_cases)

In [32]:
# Print shapes
print("Positive cases: ", positive_cases.shape)
print("Negative cases: ", negative_cases.shape)

Positive cases:  (9, 5, 5, 5)
Negative cases:  (9, 5, 5, 5)


In [5]:
# If larger than 50, do not visualize the tree do to the size (crashes the kernel)
if simulations <= 100:
    graph = dynamic_concept.view_tree()

    graph.render('./visualization/images/tree', view=True)

In [6]:
# Test if there are any duplicates accross the two sets
for i in range(len(positive_cases)):
    for j in range(len(negative_cases)):
        if np.array_equal(positive_cases[i], negative_cases[j]):
            print("Duplicate found!")
            print(positive_cases[i])
            print(negative_cases[j])
            break

In [33]:
# Find the number of any duplicates within the positive cases
duplicate_count = 0
for i in range(len(positive_cases)):
    for j in range(i + 1, len(positive_cases)):
        if np.array_equal(positive_cases[i], positive_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in positive cases: ", duplicate_count)

# Find the number of any duplicates within the negative cases
duplicate_count = 0
for i in range(len(negative_cases)):
    for j in range(i + 1, len(negative_cases)):
        if np.array_equal(negative_cases[i], negative_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in negative: ", duplicate_count)

Duplicate count in positive cases:  0
Duplicate count in negative:  0


In [ ]:
# Print all the positive cases
for i in range(len(positive_cases)):
    print(f"Positive case {i}:")
    print(positive_cases[i])
    print(gogame.str(positive_cases[i], nn_format=True))
    print()

In [ ]:
# Print all the negative cases
for i in range(len(negative_cases)):
    print(f"Negative case {i}:")
    print(negative_cases[i])
    print(gogame.str(negative_cases[i], nn_format=True))
    print()

In [34]:
BINARY = True

# First test if the concept can be regressed form the inputs
name = "input"
all_cases = np.concatenate([positive_cases, negative_cases])
all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
all_labels = np.array(all_labels)
shuffled_indices = np.arange(all_labels.shape[0])

np.random.shuffle(shuffled_indices)

all_cases = all_cases[shuffled_indices]
all_labels = all_labels[shuffled_indices]

points = all_cases.reshape(all_cases.shape[0], -1)

POSITIONS_TO_CONSIDER = points.shape[0]

print("Positions to consider: ", POSITIONS_TO_CONSIDER)

# Use the regression
score = linear_regression.perform_regression(
    points=points[:POSITIONS_TO_CONSIDER], 
    targets=all_labels[:POSITIONS_TO_CONSIDER], 
    validation_points=points[POSITIONS_TO_CONSIDER:], 
    validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
    is_binary=True,
    epochs=50,
    dynamic=True
)

print("Regression score: ", score)

# Remove the files if they exist
if os.path.exists("../concept_presences/dynamic/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
    # Test if epoch folder exists
    if os.path.exists("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
        # Remove all files in the epoch folder
        # Fist save the 
        for file in os.listdir("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
            os.remove("../concept_presences/dynamic/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name, file))

os.makedirs("../concept_presences", exist_ok=True)
os.makedirs("../concept_presences/dynamic", exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}".format(board_name), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}".format(board_name, session_name), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name), exist_ok=True)

random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

# Save concept presences in json file
with open("../concept_presences/dynamic/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, name, random_suffix), "w") as f:
    json.dump(score, f)

Positions to consider:  18
Epoch 1/50


2024-02-09 16:11:23.457220: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:23.509362: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 885ms/step - loss: 0.8389
Epoch 2/50
1/1 [==============================] - 0s 27ms/step - loss: 0.8385
Epoch 3/50
1/1 [==============================] - 0s 25ms/step - loss: 0.8380
Epoch 4/50
1/1 [==============================] - 0s 26ms/step - loss: 0.8376
Epoch 5/50
1/1 [==============================] - 0s 32ms/step - loss: 0.8371
Epoch 6/50
1/1 [==============================] - 0s 27ms/step - loss: 0.8367
Epoch 7/50
1/1 [==============================] - 0s 29ms/step - loss: 0.8362
Epoch 8/50
1/1 [==============================] - 0s 27ms/step - loss: 0.8358
Epoch 9/50
1/1 [==============================] - 0s 26ms/step - loss: 0.8353
Epoch 10/50
1/1 [==============================] - 0s 25ms/step - loss: 0.8349
Epoch 11/50
1/1 [==============================] - 0s 25ms/step - loss: 0.8344
Epoch 12/50
1/1 [==============================] - 0s 30ms/step - loss: 0.8340
Epoch 13/50
1/1 [==============================] - 0s 27ms/step - loss:

2024-02-09 16:11:25.421012: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [35]:
epochs_to_look_at = agents_to_sample

for epoch in epochs_to_look_at:
    path = full_model_path + model_name + "_" + str(epoch) + ".keras"
    model = ConvNet(board_size, path)

    # Will have a length equal to the sum of the numer of rows in the positive and negative cases arrays
    # And will contain 1s for positive cases and 0s for negative cases
    # Is used as labels/targets for the regression
    all_cases = np.concatenate([positive_cases, negative_cases])
    all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
    all_labels = np.array(all_labels)
    shuffled_indices = np.arange(all_labels.shape[0])

    np.random.shuffle(shuffled_indices)

    all_cases = all_cases[shuffled_indices]
    all_labels = all_labels[shuffled_indices]

    concept_presences = {}
    
    outputs = model.get_all_activation_values(all_cases)

    # Merge outputs
    merged_outputs = []
    for output_batch in outputs:
        for i, output_layer in enumerate(output_batch):
            if len(merged_outputs) <= i:
                merged_outputs.append([])
            merged_outputs[i].extend(output_layer)

    for i, layer_output in enumerate(merged_outputs):
        merged_outputs[i] = np.array(merged_outputs[i])
    
    outputs = merged_outputs

    # Perform regression
    concept_presence_per_layer = []
    for (i, output) in enumerate(outputs):
        points = output.reshape((output.shape[0], np.prod(output.shape[1:])))
        # So one has (n, k) samples where n is the number of positions, and k is the total number of activation values in layer i.
        print(f"Performing regression for layer {i}")
        score = linear_regression.perform_regression(
            points=points[:POSITIONS_TO_CONSIDER], 
            targets=all_labels[:POSITIONS_TO_CONSIDER], 
            validation_points=points[POSITIONS_TO_CONSIDER:], 
            validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
            is_binary=BINARY,
            epochs=100,
            dynamic=True
        )
        concept_presence_per_layer.append(score)

        print(f"The presence of {CONCEPT_NAME} in resblock {i} is {score}")
    
    concept_presences[CONCEPT_NAME] = concept_presence_per_layer

    # Remove the files if they exist
    if os.path.exists("../concept_presences/dynamic/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
        # Test if epoch folder exists
        if os.path.exists("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
            # Remove all files in the epoch folder
            # Fist save the 
            for file in os.listdir("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
                os.remove("../concept_presences/dynamic/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch, file))

    os.makedirs("../concept_presences", exist_ok=True)
    os.makedirs("../concept_presences/dynamic", exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}".format(board_name), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}".format(board_name, session_name), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch), exist_ok=True)

    random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

    # Save concept presences in json file
    with open("../concept_presences/dynamic/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, epoch, random_suffix), "w") as f:
        json.dump(concept_presences[CONCEPT_NAME], f)

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 13.45it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:11:29.283409: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:29.331766: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 850ms/step - loss: 1.1007
Epoch 2/100
1/1 [==============================] - 0s 30ms/step - loss: 1.0995
Epoch 3/100
1/1 [==============================] - 0s 34ms/step - loss: 1.0983
Epoch 4/100
1/1 [==============================] - 0s 30ms/step - loss: 1.0971
Epoch 5/100
1/1 [==============================] - 0s 35ms/step - loss: 1.0959
Epoch 6/100
1/1 [==============================] - 0s 35ms/step - loss: 1.0947
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 1.0934
Epoch 8/100
1/1 [==============================] - 0s 34ms/step - loss: 1.0922
Epoch 9/100
1/1 [==============================] - 0s 42ms/step - loss: 1.0910
Epoch 10/100
1/1 [==============================] - 0s 42ms/step - loss: 1.0898
Epoch 11/100
1/1 [==============================] - 0s 32ms/step - loss: 1.0886
Epoch 12/100
1/1 [==============================] - 0s 41ms/step - loss: 1.0874
Epoch 13/100
1/1 [==============================] - 0s 39ms/

2024-02-09 16:11:33.080924: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:33.529076: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:33.568653: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 681ms/step - loss: 1.1800
Epoch 2/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1784
Epoch 3/100
1/1 [==============================] - 0s 28ms/step - loss: 1.1768
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1752
Epoch 5/100
1/1 [==============================] - 0s 65ms/step - loss: 1.1736
Epoch 6/100
1/1 [==============================] - 0s 44ms/step - loss: 1.1720
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1704
Epoch 8/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1688
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1672
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1656
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1640
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1624
Epoch 13/100
1/1 [==============================] - 0s 31ms/

2024-02-09 16:11:37.048039: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:37.437416: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:37.470471: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 689ms/step - loss: 1.1823
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1807
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1791
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1776
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1760
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1744
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1728
Epoch 8/100
1/1 [==============================] - 0s 27ms/step - loss: 1.1712
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1697
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1681
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1665
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1650
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-09 16:11:40.410911: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 92.91it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:11:41.128577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:41.171168: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 740ms/step - loss: 1.1221
Epoch 2/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1207
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1193
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1180
Epoch 5/100
1/1 [==============================] - 0s 22ms/step - loss: 1.1166
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1152
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1139
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1125
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1112
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1098
Epoch 11/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1085
Epoch 12/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1072
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-09 16:11:44.059688: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:44.425885: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:44.466233: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 707ms/step - loss: 1.1954
Epoch 2/100
1/1 [==============================] - 0s 36ms/step - loss: 1.1936
Epoch 3/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1919
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1901
Epoch 5/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1884
Epoch 6/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1867
Epoch 7/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1850
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1833
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1816
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1798
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1782
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1765
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-09 16:11:47.850873: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:48.313156: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:48.351899: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 735ms/step - loss: 1.1759
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1742
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1725
Epoch 4/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1708
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1691
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1674
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1658
Epoch 8/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1641
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1625
Epoch 10/100
1/1 [==============================] - 0s 39ms/step - loss: 1.1608
Epoch 11/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1592
Epoch 12/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1575
Epoch 13/100
1/1 [==============================] - 0s 28ms/

2024-02-09 16:11:51.604752: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 104.98it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:11:52.282025: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:52.318452: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 749ms/step - loss: 1.1542
Epoch 2/100
1/1 [==============================] - 0s 35ms/step - loss: 1.1520
Epoch 3/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1497
Epoch 4/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1475
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1454
Epoch 6/100
1/1 [==============================] - 0s 96ms/step - loss: 1.1433
Epoch 7/100
1/1 [==============================] - 0s 65ms/step - loss: 1.1412
Epoch 8/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1391
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1370
Epoch 10/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1350
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1330
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1311
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-09 16:11:55.619649: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:56.116145: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:56.153819: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 800ms/step - loss: 1.1435
Epoch 2/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1414
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1393
Epoch 4/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1372
Epoch 5/100
1/1 [==============================] - 0s 36ms/step - loss: 1.1351
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1330
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1310
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1290
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1269
Epoch 10/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1249
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1229
Epoch 12/100
1/1 [==============================] - 0s 72ms/step - loss: 1.1209
Epoch 13/100
1/1 [==============================] - 0s 41ms/

2024-02-09 16:11:59.329869: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:59.714959: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:11:59.754121: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 695ms/step - loss: 1.2038
Epoch 2/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2016
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.1995
Epoch 4/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1973
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1952
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1930
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1909
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1887
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1866
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1845
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1824
Epoch 12/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1803
Epoch 13/100
1/1 [==============================] - 0s 26ms/

2024-02-09 16:12:02.819209: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 96.65it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:12:04.520434: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:04.565268: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 2s 2s/step - loss: 1.1361
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1341
Epoch 3/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1321
Epoch 4/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1301
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1282
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1262
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1243
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1224
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1205
Epoch 10/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1186
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1167
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1149
Epoch 13/100
1/1 [==============================] - 0s 22ms/ste

2024-02-09 16:12:08.016763: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:08.413174: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:08.457024: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 692ms/step - loss: 1.2180
Epoch 2/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2152
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2124
Epoch 4/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2096
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2069
Epoch 6/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2041
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2014
Epoch 8/100
1/1 [==============================] - 0s 27ms/step - loss: 1.1988
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1962
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1936
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1910
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1884
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-09 16:12:11.845508: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:12.243413: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:12.279409: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 743ms/step - loss: 1.1991
Epoch 2/100
1/1 [==============================] - 0s 36ms/step - loss: 1.1968
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1945
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1922
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1900
Epoch 6/100
1/1 [==============================] - 0s 30ms/step - loss: 1.1877
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1855
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1832
Epoch 9/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1810
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1788
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1765
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1743
Epoch 13/100
1/1 [==============================] - 0s 33ms/

2024-02-09 16:12:15.362888: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 98.83it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:12:15.990989: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:16.025831: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 627ms/step - loss: 1.1095
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1074
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1052
Epoch 4/100
1/1 [==============================] - 0s 31ms/step - loss: 1.1031
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1010
Epoch 6/100
1/1 [==============================] - 0s 33ms/step - loss: 1.0989
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.0968
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.0947
Epoch 9/100
1/1 [==============================] - 0s 28ms/step - loss: 1.0926
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.0906
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.0885
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.0864
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-09 16:12:19.101573: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:19.468861: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:19.502932: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 636ms/step - loss: 1.1719
Epoch 2/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1688
Epoch 3/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1657
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1627
Epoch 5/100
1/1 [==============================] - 0s 33ms/step - loss: 1.1596
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1566
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1536
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1506
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1476
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1446
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1417
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1388
Epoch 13/100
1/1 [==============================] - 0s 31ms/

2024-02-09 16:12:22.533122: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:22.901259: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:22.935643: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 626ms/step - loss: 1.2619
Epoch 2/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2591
Epoch 3/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2564
Epoch 4/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2536
Epoch 5/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2508
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2481
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2453
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2426
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2398
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2371
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2344
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2317
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-09 16:12:25.994535: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 96.99it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-09 16:12:26.593966: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:26.630185: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 642ms/step - loss: 1.1792
Epoch 2/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1762
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1732
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1703
Epoch 5/100
1/1 [==============================] - 0s 35ms/step - loss: 1.1673
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 1.1644
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1615
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1587
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1558
Epoch 10/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1530
Epoch 11/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1501
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1473
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-09 16:12:29.604874: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:29.969826: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:30.003401: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 640ms/step - loss: 1.2176
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2139
Epoch 3/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2102
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2065
Epoch 5/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2028
Epoch 6/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1992
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1955
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1919
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1884
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1848
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1812
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1777
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-09 16:12:33.107671: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:33.477511: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-09 16:12:33.513861: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 654ms/step - loss: 1.1913
Epoch 2/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1885
Epoch 3/100
1/1 [==============================] - 0s 41ms/step - loss: 1.1857
Epoch 4/100
1/1 [==============================] - 0s 39ms/step - loss: 1.1830
Epoch 5/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1802
Epoch 6/100
1/1 [==============================] - 0s 29ms/step - loss: 1.1775
Epoch 7/100
1/1 [==============================] - 0s 38ms/step - loss: 1.1748
Epoch 8/100
1/1 [==============================] - 0s 28ms/step - loss: 1.1720
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1693
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1666
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1639
Epoch 12/100
1/1 [==============================] - 0s 32ms/step - loss: 1.1612
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-09 16:12:36.573985: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
