In [142]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [143]:
import numpy as np
import os
import sys
import random
import os
import string
import json

sys.path.append(os.path.abspath(os.path.join(os.path.pardir, 'src')))

from concepts import DynamicConcepts, linear_regression
from policy import ConvNet

model_name = "net"
session_name = "endeavor"
board_size = 5
board_name = f'{board_size}x{board_size}'
simulations = 3000
concept_type_single = False # If True, mcts will only consider states for the root player.

agents_to_sample = [0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]

full_model_path = f"../models/saved_sessions/board_size_{board_size}/{session_name}/"

mcts_model_path = f"../models/best_models/board_size_{board_size}/net_1000.keras"

init_state = DynamicConcepts.opening_play(board_size)

dynamic_concept = DynamicConcepts(init_state, simulations, board_size, concept_type_single, mcts_model_path)

CONCEPT_NAME = DynamicConcepts.opening_play.__name__

INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmp2ovscbyr/assets


INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmp2ovscbyr/assets
2024-02-07 16:28:15.772348: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
2024-02-07 16:28:15.772366: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
2024-02-07 16:28:15.772560: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmp2ovscbyr
2024-02-07 16:28:15.775255: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2024-02-07 16:28:15.775267: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmp2ovscbyr
2024-02-07 16:28:15.784518: I tensorflow/cc/saved_model/loader.cc:231] Restoring SavedModel bundle.
2024-02-07 16:28:15.830935: I tensorflow/cc/saved_model/loader.cc:215] Running initialization

In [144]:
def load_model(full_name, model_name, epoch):
    model_path = full_name + model_name + "_" + str(epoch) + ".keras"
    model = ConvNet(board_size, model_path)
    return model

agents = [load_model(full_model_path, model_name, epoch) for epoch in agents_to_sample]

In [145]:
positive_cases = []
negative_cases = []

pos, neg = dynamic_concept.generate_cases()

positive_cases.extend(pos)
negative_cases.extend(neg)

# Create numpy arrays 
positive_cases = np.array(positive_cases)
negative_cases = np.array(negative_cases)

In [146]:
# Print shapes
print("Positive cases: ", positive_cases.shape)
print("Negative cases: ", negative_cases.shape)

Positive cases:  (11, 5, 5, 5)
Negative cases:  (38, 5, 5, 5)


In [147]:
# Test if there are any duplicates accross the two sets
for i in range(len(positive_cases)):
    for j in range(len(negative_cases)):
        if np.array_equal(positive_cases[i], negative_cases[j]):
            print("Duplicate found!")
            print(positive_cases[i])
            print(negative_cases[j])
            break

In [148]:
# Find the number of any duplicates within the positive cases
duplicate_count = 0
for i in range(len(positive_cases)):
    for j in range(i + 1, len(positive_cases)):
        if np.array_equal(positive_cases[i], positive_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in positive cases: ", duplicate_count)

# Find the number of any duplicates within the negative cases
duplicate_count = 0
for i in range(len(negative_cases)):
    for j in range(i + 1, len(negative_cases)):
        if np.array_equal(negative_cases[i], negative_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in negative: ", duplicate_count)

Duplicate count in positive cases:  0
Duplicate count in negative:  0


In [149]:
# Print all the positive cases
for i in range(len(positive_cases)):
    print(f"Positive case {i}:")
    print(positive_cases[i])
    print()

Positive case 0:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]

Positive case 1:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1

In [150]:
# Print all the negative cases
for i in range(len(negative_cases)):
    print(f"Negative case {i}:")
    print(negative_cases[i])
    print()

Negative case 0:
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Negative case 1:
[[[0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0

In [75]:
BINARY = True

# First test if the concept can be regressed form the inputs
name = "input"
all_cases = np.concatenate([positive_cases, negative_cases])
all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
all_labels = np.array(all_labels)
shuffled_indices = np.arange(all_labels.shape[0])

np.random.shuffle(shuffled_indices)

all_cases = all_cases[shuffled_indices]
all_labels = all_labels[shuffled_indices]

points = all_cases.reshape(all_cases.shape[0], -1)

POSITIONS_TO_CONSIDER = points.shape[0]

print("Positions to consider: ", POSITIONS_TO_CONSIDER)

# Use the regression
score = linear_regression.perform_regression(
    points=points[:POSITIONS_TO_CONSIDER], 
    targets=all_labels[:POSITIONS_TO_CONSIDER], 
    validation_points=points[POSITIONS_TO_CONSIDER:], 
    validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
    is_binary=True,
    epochs=50,
    dynamic=True
)

print("Regression score: ", score)

# Remove the files if they exist
if os.path.exists("../concept_presences/dynamic/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
    # Test if epoch folder exists
    if os.path.exists("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
        # Remove all files in the epoch folder
        # Fist save the 
        for file in os.listdir("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name)):
            os.remove("../concept_presences/dynamic/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name, file))

os.makedirs("../concept_presences", exist_ok=True)
os.makedirs("../concept_presences/dynamic", exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}".format(board_name), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}".format(board_name, session_name), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
os.makedirs("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, name), exist_ok=True)

random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

# Save concept presences in json file
with open("../concept_presences/dynamic/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, name, random_suffix), "w") as f:
    json.dump(score, f)

Positions to consider:  34
Epoch 1/50


2024-02-07 14:23:12.169333: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:12.231472: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 280ms/step - loss: 0.8064
Epoch 2/50
2/2 [==============================] - 0s 92ms/step - loss: 0.8060
Epoch 3/50
2/2 [==============================] - 0s 24ms/step - loss: 0.8058
Epoch 4/50
2/2 [==============================] - 0s 42ms/step - loss: 0.8055
Epoch 5/50
2/2 [==============================] - 0s 66ms/step - loss: 0.8053
Epoch 6/50
2/2 [==============================] - 0s 44ms/step - loss: 0.8050
Epoch 7/50
2/2 [==============================] - 0s 61ms/step - loss: 0.8048
Epoch 8/50
2/2 [==============================] - 0s 38ms/step - loss: 0.8045
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 0.8043
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 0.8040
Epoch 11/50
2/2 [==============================] - 0s 27ms/step - loss: 0.8037
Epoch 12/50
2/2 [==============================] - 0s 61ms/step - loss: 0.8034
Epoch 13/50
2/2 [==============================] - 0s 36ms/step - loss:

2024-02-07 14:23:16.369393: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


In [76]:
epochs_to_look_at = agents_to_sample

for epoch in epochs_to_look_at:
    path = full_model_path + model_name + "_" + str(epoch) + ".keras"
    model = ConvNet(board_size, path)

    # Will have a length equal to the sum of the numer of rows in the positive and negative cases arrays
    # And will contain 1s for positive cases and 0s for negative cases
    # Is used as labels/targets for the regression
    all_cases = np.concatenate([positive_cases, negative_cases])
    all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
    all_labels = np.array(all_labels)
    shuffled_indices = np.arange(all_labels.shape[0])

    np.random.shuffle(shuffled_indices)

    all_cases = all_cases[shuffled_indices]
    all_labels = all_labels[shuffled_indices]

    concept_presences = {}
    
    outputs = model.get_all_activation_values(all_cases)

    # Merge outputs
    merged_outputs = []
    for output_batch in outputs:
        for i, output_layer in enumerate(output_batch):
            if len(merged_outputs) <= i:
                merged_outputs.append([])
            merged_outputs[i].extend(output_layer)

    for i, layer_output in enumerate(merged_outputs):
        merged_outputs[i] = np.array(merged_outputs[i])
    
    outputs = merged_outputs

    # Perform regression
    concept_presence_per_layer = []
    for (i, output) in enumerate(outputs):
        points = output.reshape((output.shape[0], np.prod(output.shape[1:])))
        # So one has (n, k) samples where n is the number of positions, and k is the total number of activation values in layer i.
        print(f"Performing regression for layer {i}")
        score = linear_regression.perform_regression(
            points=points[:POSITIONS_TO_CONSIDER], 
            targets=all_labels[:POSITIONS_TO_CONSIDER], 
            validation_points=points[POSITIONS_TO_CONSIDER:], 
            validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
            is_binary=BINARY,
            epochs=50,
            dynamic=True
        )
        concept_presence_per_layer.append(score)

        print(f"The presence of {CONCEPT_NAME} in resblock {i} is {score}")
    
    concept_presences[CONCEPT_NAME] = concept_presence_per_layer

    # Remove the files if they exist
    if os.path.exists("../concept_presences/dynamic/{}/{}/{}/".format(board_name, session_name, CONCEPT_NAME)):
        # Test if epoch folder exists
        if os.path.exists("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
            # Remove all files in the epoch folder
            # Fist save the 
            for file in os.listdir("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch)):
                os.remove("../concept_presences/dynamic/{}/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch, file))

    os.makedirs("../concept_presences", exist_ok=True)
    os.makedirs("../concept_presences/dynamic", exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}".format(board_name), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}".format(board_name, session_name), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME), exist_ok=True)
    os.makedirs("../concept_presences/dynamic/{}/{}/{}/{}".format(board_name, session_name, CONCEPT_NAME, epoch), exist_ok=True)

    random_suffix = ''.join(random.choices(string.ascii_uppercase + string.digits, k=10))

    # Save concept presences in json file
    with open("../concept_presences/dynamic/{}/{}/{}/{}/{}.json".format(board_name, session_name, CONCEPT_NAME, epoch, random_suffix), "w") as f:
        json.dump(concept_presences[CONCEPT_NAME], f)

Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 24.98it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:23:36.166084: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:36.208824: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 404ms/step - loss: 1.1684
Epoch 2/50
2/2 [==============================] - 0s 66ms/step - loss: 1.1650
Epoch 3/50
2/2 [==============================] - 0s 71ms/step - loss: 1.1620
Epoch 4/50
2/2 [==============================] - 0s 73ms/step - loss: 1.1592
Epoch 5/50
2/2 [==============================] - 0s 28ms/step - loss: 1.1568
Epoch 6/50
2/2 [==============================] - 0s 75ms/step - loss: 1.1547
Epoch 7/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1524
Epoch 8/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1497
Epoch 9/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1470
Epoch 10/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1442
Epoch 11/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1413
Epoch 12/50
2/2 [==============================] - 0s 27ms/step - loss: 1.1385
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:23:40.329078: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:40.770738: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:40.813637: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 380ms/step - loss: 1.1523
Epoch 2/50
2/2 [==============================] - 0s 79ms/step - loss: 1.1492
Epoch 3/50
2/2 [==============================] - 0s 85ms/step - loss: 1.1464
Epoch 4/50
2/2 [==============================] - 0s 51ms/step - loss: 1.1437
Epoch 5/50
2/2 [==============================] - 0s 86ms/step - loss: 1.1410
Epoch 6/50
2/2 [==============================] - 0s 39ms/step - loss: 1.1386
Epoch 7/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1360
Epoch 8/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1334
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1307
Epoch 10/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1280
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1254
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1226
Epoch 13/50
2/2 [==============================] - 0s 27ms/step - loss:

2024-02-07 14:23:44.783761: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:45.247760: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:45.291652: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 374ms/step - loss: 1.1844
Epoch 2/50
2/2 [==============================] - 0s 40ms/step - loss: 1.1811
Epoch 3/50
2/2 [==============================] - 0s 87ms/step - loss: 1.1780
Epoch 4/50
2/2 [==============================] - 0s 41ms/step - loss: 1.1749
Epoch 5/50
2/2 [==============================] - 0s 45ms/step - loss: 1.1719
Epoch 6/50
2/2 [==============================] - 0s 31ms/step - loss: 1.1689
Epoch 7/50
2/2 [==============================] - 0s 61ms/step - loss: 1.1658
Epoch 8/50
2/2 [==============================] - 0s 35ms/step - loss: 1.1628
Epoch 9/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1599
Epoch 10/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1571
Epoch 11/50
2/2 [==============================] - 0s 70ms/step - loss: 1.1543
Epoch 12/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1515
Epoch 13/50
2/2 [==============================] - 0s 21ms/step - loss:

2024-02-07 14:23:49.133148: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 105.18it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:23:49.794186: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:49.840031: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 440ms/step - loss: 1.1224
Epoch 2/50
2/2 [==============================] - 0s 71ms/step - loss: 1.1180
Epoch 3/50
2/2 [==============================] - 0s 62ms/step - loss: 1.1144
Epoch 4/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1107
Epoch 5/50
2/2 [==============================] - 0s 45ms/step - loss: 1.1067
Epoch 6/50
2/2 [==============================] - 0s 34ms/step - loss: 1.1026
Epoch 7/50
2/2 [==============================] - 0s 30ms/step - loss: 1.0984
Epoch 8/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0945
Epoch 9/50
2/2 [==============================] - 0s 70ms/step - loss: 1.0909
Epoch 10/50
2/2 [==============================] - 0s 27ms/step - loss: 1.0870
Epoch 11/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0841
Epoch 12/50
2/2 [==============================] - 0s 40ms/step - loss: 1.0810
Epoch 13/50
2/2 [==============================] - 0s 25ms/step - loss:

2024-02-07 14:23:53.800239: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:54.215001: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:54.258933: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 341ms/step - loss: 1.1426
Epoch 2/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1369
Epoch 3/50
2/2 [==============================] - 0s 71ms/step - loss: 1.1321
Epoch 4/50
2/2 [==============================] - 0s 65ms/step - loss: 1.1279
Epoch 5/50
2/2 [==============================] - 0s 45ms/step - loss: 1.1238
Epoch 6/50
2/2 [==============================] - 0s 36ms/step - loss: 1.1205
Epoch 7/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1172
Epoch 8/50
2/2 [==============================] - 0s 25ms/step - loss: 1.1144
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1115
Epoch 10/50
2/2 [==============================] - 0s 40ms/step - loss: 1.1088
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1062
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1040
Epoch 13/50
2/2 [==============================] - 0s 25ms/step - loss:

2024-02-07 14:23:57.999907: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:58.380934: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:23:58.421180: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 362ms/step - loss: 1.1951
Epoch 2/50
2/2 [==============================] - 0s 92ms/step - loss: 1.1888
Epoch 3/50
2/2 [==============================] - 0s 66ms/step - loss: 1.1835
Epoch 4/50
2/2 [==============================] - 0s 31ms/step - loss: 1.1783
Epoch 5/50
2/2 [==============================] - 0s 43ms/step - loss: 1.1737
Epoch 6/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1692
Epoch 7/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1653
Epoch 8/50
2/2 [==============================] - 0s 56ms/step - loss: 1.1611
Epoch 9/50
2/2 [==============================] - 0s 56ms/step - loss: 1.1577
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1547
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1518
Epoch 12/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1488
Epoch 13/50
2/2 [==============================] - 0s 21ms/step - loss:

2024-02-07 14:24:02.076822: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 86.75it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:24:02.670489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:02.710849: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 280ms/step - loss: 1.1066
Epoch 2/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1014
Epoch 3/50
2/2 [==============================] - 0s 38ms/step - loss: 1.0971
Epoch 4/50
2/2 [==============================] - 0s 59ms/step - loss: 1.0926
Epoch 5/50
2/2 [==============================] - 0s 44ms/step - loss: 1.0883
Epoch 6/50
2/2 [==============================] - 0s 61ms/step - loss: 1.0842
Epoch 7/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0803
Epoch 8/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0766
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0730
Epoch 10/50
2/2 [==============================] - 0s 41ms/step - loss: 1.0694
Epoch 11/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0659
Epoch 12/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0632
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:24:06.503853: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:06.908324: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:06.943086: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 357ms/step - loss: 1.2034
Epoch 2/50
2/2 [==============================] - 0s 44ms/step - loss: 1.1947
Epoch 3/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1874
Epoch 4/50
2/2 [==============================] - 0s 73ms/step - loss: 1.1803
Epoch 5/50
2/2 [==============================] - 0s 46ms/step - loss: 1.1742
Epoch 6/50
2/2 [==============================] - 0s 69ms/step - loss: 1.1678
Epoch 7/50
2/2 [==============================] - 0s 77ms/step - loss: 1.1626
Epoch 8/50
2/2 [==============================] - 0s 66ms/step - loss: 1.1574
Epoch 9/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1527
Epoch 10/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1485
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1446
Epoch 12/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1409
Epoch 13/50
2/2 [==============================] - 0s 22ms/step - loss:

2024-02-07 14:24:10.613223: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:11.100812: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:11.143541: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 365ms/step - loss: 1.2376
Epoch 2/50
2/2 [==============================] - 0s 32ms/step - loss: 1.2317
Epoch 3/50
2/2 [==============================] - 0s 59ms/step - loss: 1.2269
Epoch 4/50
2/2 [==============================] - 0s 45ms/step - loss: 1.2224
Epoch 5/50
2/2 [==============================] - 0s 36ms/step - loss: 1.2189
Epoch 6/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2153
Epoch 7/50
2/2 [==============================] - 0s 36ms/step - loss: 1.2114
Epoch 8/50
2/2 [==============================] - 0s 26ms/step - loss: 1.2077
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2039
Epoch 10/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2005
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1970
Epoch 12/50
2/2 [==============================] - 0s 29ms/step - loss: 1.1935
Epoch 13/50
2/2 [==============================] - 0s 47ms/step - loss:

2024-02-07 14:24:14.885659: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 107.71it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:24:15.509379: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:15.551723: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 477ms/step - loss: 1.1033
Epoch 2/50
2/2 [==============================] - 0s 96ms/step - loss: 1.0968
Epoch 3/50
2/2 [==============================] - 0s 51ms/step - loss: 1.0909
Epoch 4/50
2/2 [==============================] - 0s 48ms/step - loss: 1.0853
Epoch 5/50
2/2 [==============================] - 0s 30ms/step - loss: 1.0806
Epoch 6/50
2/2 [==============================] - 0s 31ms/step - loss: 1.0762
Epoch 7/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0727
Epoch 8/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0700
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0674
Epoch 10/50
2/2 [==============================] - 0s 78ms/step - loss: 1.0649
Epoch 11/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0621
Epoch 12/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0592
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:24:19.415646: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:19.818751: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:19.854064: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 315ms/step - loss: 1.1216
Epoch 2/50
2/2 [==============================] - 0s 51ms/step - loss: 1.1155
Epoch 3/50
2/2 [==============================] - 0s 54ms/step - loss: 1.1104
Epoch 4/50
2/2 [==============================] - 0s 55ms/step - loss: 1.1056
Epoch 5/50
2/2 [==============================] - 0s 67ms/step - loss: 1.1007
Epoch 6/50
2/2 [==============================] - 0s 48ms/step - loss: 1.0963
Epoch 7/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0923
Epoch 8/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0883
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0845
Epoch 10/50
2/2 [==============================] - 0s 42ms/step - loss: 1.0808
Epoch 11/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0774
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0737
Epoch 13/50
2/2 [==============================] - 0s 35ms/step - loss:

2024-02-07 14:24:23.463832: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:23.864477: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:23.898090: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 259ms/step - loss: 1.1200
Epoch 2/50
2/2 [==============================] - 0s 67ms/step - loss: 1.1139
Epoch 3/50
2/2 [==============================] - 0s 99ms/step - loss: 1.1086
Epoch 4/50
2/2 [==============================] - 0s 28ms/step - loss: 1.1042
Epoch 5/50
2/2 [==============================] - 0s 62ms/step - loss: 1.0996
Epoch 6/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0953
Epoch 7/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0910
Epoch 8/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0868
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0826
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0786
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0748
Epoch 12/50
2/2 [==============================] - 0s 34ms/step - loss: 1.0706
Epoch 13/50
2/2 [==============================] - 0s 59ms/step - loss:

2024-02-07 14:24:27.579826: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 105.83it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:24:29.161900: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:29.214066: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 226ms/step - loss: 1.2597
Epoch 2/50
2/2 [==============================] - 0s 69ms/step - loss: 1.2493
Epoch 3/50
2/2 [==============================] - 0s 82ms/step - loss: 1.2414
Epoch 4/50
2/2 [==============================] - 0s 31ms/step - loss: 1.2351
Epoch 5/50
2/2 [==============================] - 0s 61ms/step - loss: 1.2285
Epoch 6/50
2/2 [==============================] - 0s 37ms/step - loss: 1.2211
Epoch 7/50
2/2 [==============================] - 0s 26ms/step - loss: 1.2140
Epoch 8/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2064
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1996
Epoch 10/50
2/2 [==============================] - 0s 80ms/step - loss: 1.1930
Epoch 11/50
2/2 [==============================] - 0s 34ms/step - loss: 1.1855
Epoch 12/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1785
Epoch 13/50
2/2 [==============================] - 0s 24ms/step - loss:

2024-02-07 14:24:33.056058: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:33.435071: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:33.468669: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 284ms/step - loss: 1.2858
Epoch 2/50
2/2 [==============================] - 0s 51ms/step - loss: 1.2716
Epoch 3/50
2/2 [==============================] - 0s 56ms/step - loss: 1.2584
Epoch 4/50
2/2 [==============================] - 0s 27ms/step - loss: 1.2475
Epoch 5/50
2/2 [==============================] - 0s 69ms/step - loss: 1.2386
Epoch 6/50
2/2 [==============================] - 0s 52ms/step - loss: 1.2292
Epoch 7/50
2/2 [==============================] - 0s 24ms/step - loss: 1.2224
Epoch 8/50
2/2 [==============================] - 0s 31ms/step - loss: 1.2161
Epoch 9/50
2/2 [==============================] - 0s 21ms/step - loss: 1.2099
Epoch 10/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2031
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1968
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1894
Epoch 13/50
2/2 [==============================] - 0s 88ms/step - loss:

2024-02-07 14:24:37.135070: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:37.542415: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:37.579120: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 389ms/step - loss: 1.2182
Epoch 2/50
2/2 [==============================] - 0s 36ms/step - loss: 1.2092
Epoch 3/50
2/2 [==============================] - 0s 164ms/step - loss: 1.2013
Epoch 4/50
2/2 [==============================] - 0s 58ms/step - loss: 1.1941
Epoch 5/50
2/2 [==============================] - 0s 41ms/step - loss: 1.1872
Epoch 6/50
2/2 [==============================] - 0s 100ms/step - loss: 1.1809
Epoch 7/50
2/2 [==============================] - 0s 43ms/step - loss: 1.1744
Epoch 8/50
2/2 [==============================] - 0s 29ms/step - loss: 1.1686
Epoch 9/50
2/2 [==============================] - 0s 70ms/step - loss: 1.1629
Epoch 10/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1572
Epoch 11/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1519
Epoch 12/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1465
Epoch 13/50
2/2 [==============================] - 0s 35ms/step - los

2024-02-07 14:24:41.609472: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 92.48it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:24:42.247593: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:42.280890: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 390ms/step - loss: 1.1403
Epoch 2/50
2/2 [==============================] - 0s 85ms/step - loss: 1.1310
Epoch 3/50
2/2 [==============================] - 0s 38ms/step - loss: 1.1227
Epoch 4/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1151
Epoch 5/50
2/2 [==============================] - 0s 26ms/step - loss: 1.1080
Epoch 6/50
2/2 [==============================] - 0s 25ms/step - loss: 1.1017
Epoch 7/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0961
Epoch 8/50
2/2 [==============================] - 0s 57ms/step - loss: 1.0906
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0856
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0807
Epoch 11/50
2/2 [==============================] - 0s 59ms/step - loss: 1.0764
Epoch 12/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0715
Epoch 13/50
2/2 [==============================] - 0s 35ms/step - loss:

2024-02-07 14:24:45.861909: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:46.222208: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:46.254625: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 258ms/step - loss: 1.2396
Epoch 2/50
2/2 [==============================] - 0s 64ms/step - loss: 1.2210
Epoch 3/50
2/2 [==============================] - 0s 87ms/step - loss: 1.2047
Epoch 4/50
2/2 [==============================] - 0s 59ms/step - loss: 1.1907
Epoch 5/50
2/2 [==============================] - 0s 29ms/step - loss: 1.1773
Epoch 6/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1644
Epoch 7/50
2/2 [==============================] - 0s 23ms/step - loss: 1.1526
Epoch 8/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1409
Epoch 9/50
2/2 [==============================] - 0s 62ms/step - loss: 1.1306
Epoch 10/50
2/2 [==============================] - 0s 25ms/step - loss: 1.1205
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1116
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1021
Epoch 13/50
2/2 [==============================] - 0s 24ms/step - loss:

2024-02-07 14:24:49.688416: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:50.106295: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:50.154139: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 320ms/step - loss: 1.3720
Epoch 2/50
2/2 [==============================] - 0s 88ms/step - loss: 1.3585
Epoch 3/50
2/2 [==============================] - 0s 44ms/step - loss: 1.3468
Epoch 4/50
2/2 [==============================] - 0s 24ms/step - loss: 1.3349
Epoch 5/50
2/2 [==============================] - 0s 25ms/step - loss: 1.3230
Epoch 6/50
2/2 [==============================] - 0s 34ms/step - loss: 1.3117
Epoch 7/50
2/2 [==============================] - 0s 34ms/step - loss: 1.3002
Epoch 8/50
2/2 [==============================] - 0s 55ms/step - loss: 1.2900
Epoch 9/50
2/2 [==============================] - 0s 24ms/step - loss: 1.2801
Epoch 10/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2703
Epoch 11/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2614
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2524
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:24:53.616507: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 94.58it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:24:54.252655: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:54.288617: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 311ms/step - loss: 1.0244
Epoch 2/50
2/2 [==============================] - 0s 26ms/step - loss: 1.0194
Epoch 3/50
2/2 [==============================] - 0s 50ms/step - loss: 1.0154
Epoch 4/50
2/2 [==============================] - 0s 35ms/step - loss: 1.0118
Epoch 5/50
2/2 [==============================] - 0s 64ms/step - loss: 1.0088
Epoch 6/50
2/2 [==============================] - 0s 33ms/step - loss: 1.0058
Epoch 7/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0029
Epoch 8/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0001
Epoch 9/50
2/2 [==============================] - 0s 24ms/step - loss: 0.9974
Epoch 10/50
2/2 [==============================] - 0s 68ms/step - loss: 0.9948
Epoch 11/50
2/2 [==============================] - 0s 36ms/step - loss: 0.9923
Epoch 12/50
2/2 [==============================] - 0s 24ms/step - loss: 0.9899
Epoch 13/50
2/2 [==============================] - 0s 24ms/step - loss:

2024-02-07 14:24:57.939521: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:58.310147: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:24:58.347023: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 343ms/step - loss: 1.1953
Epoch 2/50
2/2 [==============================] - 0s 29ms/step - loss: 1.1838
Epoch 3/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1746
Epoch 4/50
2/2 [==============================] - 0s 41ms/step - loss: 1.1667
Epoch 5/50
2/2 [==============================] - 0s 61ms/step - loss: 1.1595
Epoch 6/50
2/2 [==============================] - 0s 57ms/step - loss: 1.1537
Epoch 7/50
2/2 [==============================] - 0s 20ms/step - loss: 1.1484
Epoch 8/50
2/2 [==============================] - 0s 31ms/step - loss: 1.1442
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1395
Epoch 10/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1344
Epoch 11/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1298
Epoch 12/50
2/2 [==============================] - 0s 25ms/step - loss: 1.1257
Epoch 13/50
2/2 [==============================] - 0s 37ms/step - loss:

2024-02-07 14:25:01.906830: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:02.266923: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:02.299560: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 340ms/step - loss: 1.3127
Epoch 2/50
2/2 [==============================] - 0s 83ms/step - loss: 1.2968
Epoch 3/50
2/2 [==============================] - 0s 31ms/step - loss: 1.2834
Epoch 4/50
2/2 [==============================] - 0s 74ms/step - loss: 1.2704
Epoch 5/50
2/2 [==============================] - 0s 50ms/step - loss: 1.2579
Epoch 6/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2466
Epoch 7/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2360
Epoch 8/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2266
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2177
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2087
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.1991
Epoch 12/50
2/2 [==============================] - 0s 29ms/step - loss: 1.1896
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:25:05.765478: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 117.12it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:25:06.372651: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:06.405669: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 379ms/step - loss: 1.0836
Epoch 2/50
2/2 [==============================] - 0s 65ms/step - loss: 1.0775
Epoch 3/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0740
Epoch 4/50
2/2 [==============================] - 0s 77ms/step - loss: 1.0698
Epoch 5/50
2/2 [==============================] - 0s 65ms/step - loss: 1.0652
Epoch 6/50
2/2 [==============================] - 0s 51ms/step - loss: 1.0600
Epoch 7/50
2/2 [==============================] - 0s 31ms/step - loss: 1.0553
Epoch 8/50
2/2 [==============================] - 0s 37ms/step - loss: 1.0508
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0462
Epoch 10/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0419
Epoch 11/50
2/2 [==============================] - 0s 28ms/step - loss: 1.0382
Epoch 12/50
2/2 [==============================] - 0s 26ms/step - loss: 1.0344
Epoch 13/50
2/2 [==============================] - 0s 24ms/step - loss:

2024-02-07 14:25:10.163085: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:10.560432: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:10.593548: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 400ms/step - loss: 1.5350
Epoch 2/50
2/2 [==============================] - 0s 87ms/step - loss: 1.5017
Epoch 3/50
2/2 [==============================] - 0s 69ms/step - loss: 1.4731
Epoch 4/50
2/2 [==============================] - 0s 32ms/step - loss: 1.4481
Epoch 5/50
2/2 [==============================] - 0s 54ms/step - loss: 1.4257
Epoch 6/50
2/2 [==============================] - 0s 27ms/step - loss: 1.4031
Epoch 7/50
2/2 [==============================] - 0s 43ms/step - loss: 1.3833
Epoch 8/50
2/2 [==============================] - 0s 40ms/step - loss: 1.3630
Epoch 9/50
2/2 [==============================] - 0s 25ms/step - loss: 1.3447
Epoch 10/50
2/2 [==============================] - 0s 38ms/step - loss: 1.3267
Epoch 11/50
2/2 [==============================] - 0s 26ms/step - loss: 1.3097
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2933
Epoch 13/50
2/2 [==============================] - 0s 22ms/step - loss:

2024-02-07 14:25:14.442408: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:14.826818: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:14.863117: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 354ms/step - loss: 1.1478
Epoch 2/50
2/2 [==============================] - 0s 58ms/step - loss: 1.1334
Epoch 3/50
2/2 [==============================] - 0s 69ms/step - loss: 1.1218
Epoch 4/50
2/2 [==============================] - 0s 30ms/step - loss: 1.1109
Epoch 5/50
2/2 [==============================] - 0s 105ms/step - loss: 1.1003
Epoch 6/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0899
Epoch 7/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0806
Epoch 8/50
2/2 [==============================] - 0s 20ms/step - loss: 1.0716
Epoch 9/50
2/2 [==============================] - 0s 20ms/step - loss: 1.0631
Epoch 10/50
2/2 [==============================] - 0s 55ms/step - loss: 1.0550
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0472
Epoch 12/50
2/2 [==============================] - 0s 22ms/step - loss: 1.0399
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss

2024-02-07 14:25:18.528865: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 108.60it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:25:19.221764: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:19.258089: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 312ms/step - loss: 1.1407
Epoch 2/50
2/2 [==============================] - 0s 49ms/step - loss: 1.1298
Epoch 3/50
2/2 [==============================] - 0s 38ms/step - loss: 1.1200
Epoch 4/50
2/2 [==============================] - 0s 62ms/step - loss: 1.1109
Epoch 5/50
2/2 [==============================] - 0s 59ms/step - loss: 1.1026
Epoch 6/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0952
Epoch 7/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0891
Epoch 8/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0829
Epoch 9/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0768
Epoch 10/50
2/2 [==============================] - 0s 77ms/step - loss: 1.0703
Epoch 11/50
2/2 [==============================] - 0s 62ms/step - loss: 1.0651
Epoch 12/50
2/2 [==============================] - 0s 21ms/step - loss: 1.0593
Epoch 13/50
2/2 [==============================] - 0s 22ms/step - loss:

2024-02-07 14:25:22.685577: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:23.120338: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:23.153687: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 336ms/step - loss: 1.5341
Epoch 2/50
2/2 [==============================] - 0s 62ms/step - loss: 1.5143
Epoch 3/50
2/2 [==============================] - 0s 29ms/step - loss: 1.5005
Epoch 4/50
2/2 [==============================] - 0s 39ms/step - loss: 1.4894
Epoch 5/50
2/2 [==============================] - 0s 54ms/step - loss: 1.4801
Epoch 6/50
2/2 [==============================] - 0s 24ms/step - loss: 1.4694
Epoch 7/50
2/2 [==============================] - 0s 25ms/step - loss: 1.4585
Epoch 8/50
2/2 [==============================] - 0s 25ms/step - loss: 1.4484
Epoch 9/50
2/2 [==============================] - 0s 28ms/step - loss: 1.4388
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.4285
Epoch 11/50
2/2 [==============================] - 0s 21ms/step - loss: 1.4173
Epoch 12/50
2/2 [==============================] - 0s 42ms/step - loss: 1.4061
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:25:26.924366: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:27.376214: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:27.420342: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 342ms/step - loss: 1.2648
Epoch 2/50
2/2 [==============================] - 0s 66ms/step - loss: 1.2479
Epoch 3/50
2/2 [==============================] - 0s 59ms/step - loss: 1.2355
Epoch 4/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2234
Epoch 5/50
2/2 [==============================] - 0s 80ms/step - loss: 1.2128
Epoch 6/50
2/2 [==============================] - 0s 31ms/step - loss: 1.2025
Epoch 7/50
2/2 [==============================] - 0s 33ms/step - loss: 1.1922
Epoch 8/50
2/2 [==============================] - 0s 59ms/step - loss: 1.1825
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1731
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.1641
Epoch 11/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1554
Epoch 12/50
2/2 [==============================] - 0s 21ms/step - loss: 1.1469
Epoch 13/50
2/2 [==============================] - 0s 20ms/step - loss:

2024-02-07 14:25:31.218697: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 105.33it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:25:31.812384: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:31.844618: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 270ms/step - loss: 1.3347
Epoch 2/50
2/2 [==============================] - 0s 58ms/step - loss: 1.3202
Epoch 3/50
2/2 [==============================] - 0s 80ms/step - loss: 1.3079
Epoch 4/50
2/2 [==============================] - 0s 46ms/step - loss: 1.2954
Epoch 5/50
2/2 [==============================] - 0s 59ms/step - loss: 1.2829
Epoch 6/50
2/2 [==============================] - 0s 60ms/step - loss: 1.2704
Epoch 7/50
2/2 [==============================] - 0s 60ms/step - loss: 1.2582
Epoch 8/50
2/2 [==============================] - 0s 25ms/step - loss: 1.2471
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.2358
Epoch 10/50
2/2 [==============================] - 0s 24ms/step - loss: 1.2253
Epoch 11/50
2/2 [==============================] - 0s 59ms/step - loss: 1.2160
Epoch 12/50
2/2 [==============================] - 0s 21ms/step - loss: 1.2068
Epoch 13/50
2/2 [==============================] - 0s 20ms/step - loss:

2024-02-07 14:25:35.484765: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:35.915256: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:35.947718: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 344ms/step - loss: 1.6227
Epoch 2/50
2/2 [==============================] - 0s 68ms/step - loss: 1.5774
Epoch 3/50
2/2 [==============================] - 0s 116ms/step - loss: 1.5399
Epoch 4/50
2/2 [==============================] - 0s 84ms/step - loss: 1.5055
Epoch 5/50
2/2 [==============================] - 0s 32ms/step - loss: 1.4769
Epoch 6/50
2/2 [==============================] - 0s 22ms/step - loss: 1.4483
Epoch 7/50
2/2 [==============================] - 0s 24ms/step - loss: 1.4218
Epoch 8/50
2/2 [==============================] - 0s 25ms/step - loss: 1.3963
Epoch 9/50
2/2 [==============================] - 0s 28ms/step - loss: 1.3723
Epoch 10/50
2/2 [==============================] - 0s 22ms/step - loss: 1.3476
Epoch 11/50
2/2 [==============================] - 0s 25ms/step - loss: 1.3246
Epoch 12/50
2/2 [==============================] - 0s 69ms/step - loss: 1.3025
Epoch 13/50
2/2 [==============================] - 0s 24ms/step - loss

2024-02-07 14:25:39.675533: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:40.077969: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:40.111569: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 326ms/step - loss: 1.3734
Epoch 2/50
2/2 [==============================] - 0s 115ms/step - loss: 1.3579
Epoch 3/50
2/2 [==============================] - 0s 38ms/step - loss: 1.3453
Epoch 4/50
2/2 [==============================] - 0s 78ms/step - loss: 1.3339
Epoch 5/50
2/2 [==============================] - 0s 58ms/step - loss: 1.3234
Epoch 6/50
2/2 [==============================] - 0s 21ms/step - loss: 1.3132
Epoch 7/50
2/2 [==============================] - 0s 29ms/step - loss: 1.3042
Epoch 8/50
2/2 [==============================] - 0s 67ms/step - loss: 1.2953
Epoch 9/50
2/2 [==============================] - 0s 23ms/step - loss: 1.2867
Epoch 10/50
2/2 [==============================] - 0s 21ms/step - loss: 1.2784
Epoch 11/50
2/2 [==============================] - 0s 20ms/step - loss: 1.2697
Epoch 12/50
2/2 [==============================] - 0s 25ms/step - loss: 1.2615
Epoch 13/50
2/2 [==============================] - 0s 21ms/step - loss

2024-02-07 14:25:43.881285: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Getting activation outputs: 100%|██████████| 2/2 [00:00<00:00, 106.57it/s]

Performing regression for layer 0
Epoch 1/50



2024-02-07 14:25:44.495578: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:44.528937: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 394ms/step - loss: 1.1020
Epoch 2/50
2/2 [==============================] - 0s 86ms/step - loss: 1.0951
Epoch 3/50
2/2 [==============================] - 0s 37ms/step - loss: 1.0893
Epoch 4/50
2/2 [==============================] - 0s 25ms/step - loss: 1.0842
Epoch 5/50
2/2 [==============================] - 0s 65ms/step - loss: 1.0797
Epoch 6/50
2/2 [==============================] - 0s 35ms/step - loss: 1.0754
Epoch 7/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0712
Epoch 8/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0674
Epoch 9/50
2/2 [==============================] - 0s 50ms/step - loss: 1.0636
Epoch 10/50
2/2 [==============================] - 0s 55ms/step - loss: 1.0598
Epoch 11/50
2/2 [==============================] - 0s 66ms/step - loss: 1.0556
Epoch 12/50
2/2 [==============================] - 0s 23ms/step - loss: 1.0517
Epoch 13/50
2/2 [==============================] - 0s 61ms/step - loss:

2024-02-07 14:25:48.395992: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:48.882227: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:48.924011: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 2s 375ms/step - loss: 1.1446
Epoch 2/50
2/2 [==============================] - 0s 197ms/step - loss: 1.1266
Epoch 3/50
2/2 [==============================] - 0s 137ms/step - loss: 1.1132
Epoch 4/50
2/2 [==============================] - 0s 78ms/step - loss: 1.1009
Epoch 5/50
2/2 [==============================] - 0s 81ms/step - loss: 1.0909
Epoch 6/50
2/2 [==============================] - 0s 32ms/step - loss: 1.0816
Epoch 7/50
2/2 [==============================] - 0s 28ms/step - loss: 1.0730
Epoch 8/50
2/2 [==============================] - 0s 44ms/step - loss: 1.0647
Epoch 9/50
2/2 [==============================] - 0s 29ms/step - loss: 1.0563
Epoch 10/50
2/2 [==============================] - 0s 26ms/step - loss: 1.0490
Epoch 11/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0416
Epoch 12/50
2/2 [==============================] - 0s 24ms/step - loss: 1.0346
Epoch 13/50
2/2 [==============================] - 0s 35ms/step - los

2024-02-07 14:25:53.196708: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:53.580848: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2024-02-07 14:25:53.613968: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


2/2 [==============================] - 1s 369ms/step - loss: 1.6406
Epoch 2/50
2/2 [==============================] - 0s 67ms/step - loss: 1.6186
Epoch 3/50
2/2 [==============================] - 0s 63ms/step - loss: 1.5999
Epoch 4/50
2/2 [==============================] - 0s 18ms/step - loss: 1.5830
Epoch 5/50
2/2 [==============================] - 0s 29ms/step - loss: 1.5673
Epoch 6/50
2/2 [==============================] - 0s 27ms/step - loss: 1.5506
Epoch 7/50
2/2 [==============================] - 0s 27ms/step - loss: 1.5371
Epoch 8/50
2/2 [==============================] - 0s 39ms/step - loss: 1.5230
Epoch 9/50
2/2 [==============================] - 0s 22ms/step - loss: 1.5104
Epoch 10/50
2/2 [==============================] - 0s 67ms/step - loss: 1.4979
Epoch 11/50
2/2 [==============================] - 0s 69ms/step - loss: 1.4860
Epoch 12/50
2/2 [==============================] - 0s 34ms/step - loss: 1.4746
Epoch 13/50
2/2 [==============================] - 0s 23ms/step - loss:

2024-02-07 14:25:57.666892: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
