In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
import os
import sys
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # or any {'0', '1', '2'}
sys.path.append(os.path.abspath(os.path.join(os.path.pardir, 'src')))
from policy import ConvNet, ResNet
from concepts import DynamicConcepts, linear_regression
import absl.logging
import numpy as np
from env import gogame
import tensorflow as tf
from utils import concept_folder_setup_and_score

absl.logging.set_verbosity(absl.logging.ERROR)

# Set memory growth
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

session_name = "falcon"
model_name = "net"
board_size = 7
board_name = f'{board_size}x{board_size}'
agents_to_sample = [0, 10, 20, 60, 100, 500]
resnet = True
random_subpar_rollout = True

model_type = "resnet" if resnet else "convnet"

# Mcts simulations
simulations = 2000

full_model_path = f"../models/saved_sessions/{model_type}/board_size_{board_size}/{session_name}/"

# Search for the model with the most seen games and use it for mcts simulations
folders = os.listdir(full_model_path)

# Sort the folders by the number in the name
sorted_folders = sorted(folders, key=lambda x: int(x.split('_')[-1].strip('.keras')))

# Get the last folder
mcts_model_path = full_model_path + sorted_folders[-1]

init_state, concept_type_single, concept_name = DynamicConcepts.end_game(board_size)

print("Initial state:\n", gogame.str(init_state))

dynamic_concept = DynamicConcepts(init_state, simulations, board_size, concept_type_single, mcts_model_path, random_subpar_rollout, resnet)

Initial state:
 	0 1 2 3 4 5 6 
0	╔═╤═╤═╤═╤═○═╗
1	╟─┼─┼─○─●─○─●
2	╟─┼─┼─○─○─●─╢
3	╟─○─┼─○─●─┼─●
4	╟─○─●─○─●─┼─╢
5	╟─○─●─●─┼─┼─╢
6	╚═●═╧═╧═╧═╧═╝
	Turn: BLACK, Game State (ONGOING|PASSED|END): ONGOING
	Black Area: 10, White Area: 22

INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpl4ubiyq4/assets


INFO:tensorflow:Assets written to: /var/folders/k4/t2xnyks517g9v60tdd71p4_00000gn/T/tmpl4ubiyq4/assets


In [18]:
positive_cases = []
negative_cases = []

pos, neg = dynamic_concept.generate_cases()

positive_cases.extend(pos)
negative_cases.extend(neg)

# Create numpy arrays
positive_cases = np.array(positive_cases)
negative_cases = np.array(negative_cases)

In [19]:
# Print shapes
print("Positive cases: ", positive_cases.shape)
print("Negative cases: ", negative_cases.shape)

Positive cases:  (11, 5, 7, 7)
Negative cases:  (18, 5, 7, 7)


In [236]:
# If larger than 50, do not visualize the tree do to the size (crashes the kernel)
if simulations <= 100:
    graph = dynamic_concept.view_tree()

    graph.render('./visualization/images/tree', view=True)

In [36]:
# Test if there are any duplicates accross the two sets
for i in range(len(positive_cases)):
    for j in range(len(negative_cases)):
        if np.array_equal(positive_cases[i], negative_cases[j]):
            print("Duplicate found!")
            print(positive_cases[i])
            print(negative_cases[j])
            break

In [20]:
# Find the number of any duplicates within the positive cases
duplicate_count = 0
for i in range(len(positive_cases)):
    for j in range(i + 1, len(positive_cases)):
        if np.array_equal(positive_cases[i], positive_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in positive cases: ", duplicate_count)

# Find the number of any duplicates within the negative cases
duplicate_count = 0
for i in range(len(negative_cases)):
    for j in range(i + 1, len(negative_cases)):
        if np.array_equal(negative_cases[i], negative_cases[j]):
            duplicate_count += 1
            break

print("Duplicate count in negative: ", duplicate_count)

Duplicate count in positive cases:  0
Duplicate count in negative:  0


In [21]:
# Print all the positive cases
for i in range(len(positive_cases)):
    print(f"Positive case {i}:")
    print(positive_cases[i])
    print(gogame.str(positive_cases[i], nn_format=True))
    print()

Positive case 0:
[[[0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 1. 0.]
  [0. 0. 0. 1. 1. 0. 0.]
  [0. 1. 0. 1. 0. 0. 0.]
  [0. 1. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 1.]
  [0. 0. 1. 0. 1. 0. 0.]
  [0. 0. 1. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
	0 1 2 3 4 5 6 
0	╔═╤═╤═╤═╤═○═╗
1	╟─┼─┼─○─●─○─●
2	╟─┼─┼─○─○─●─╢
3	╟─○─┼─○─●─┼─●
4	╟─○─●─○─●─┼─╢
5	

In [ ]:
# Print all the negative cases
for i in range(len(negative_cases)):
    print(f"Negative case {i}:")
    print(negative_cases[i])
    print(gogame.str(negative_cases[i], nn_format=True))
    print()

In [23]:
# Probing
BINARY = True
epochs = 100

In [26]:
# First test if the concept can be regressed form the inputs
name = "input"
all_cases = np.concatenate([positive_cases, negative_cases])
all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
all_labels = np.array(all_labels)
shuffled_indices = np.arange(all_labels.shape[0])

np.random.shuffle(shuffled_indices)

all_cases = all_cases[shuffled_indices]
all_labels = all_labels[shuffled_indices]

points = all_cases.reshape(all_cases.shape[0], -1)

POSITIONS_TO_CONSIDER = points.shape[0]

print("Positions to consider: ", POSITIONS_TO_CONSIDER)

# Use the regression
score = linear_regression.perform_regression(
    points=points[:POSITIONS_TO_CONSIDER], 
    targets=all_labels[:POSITIONS_TO_CONSIDER], 
    validation_points=points[POSITIONS_TO_CONSIDER:], 
    validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
    is_binary=True,
    epochs=epochs,
    dynamic=True
)

score = 0 if score < 0 else score

print("Regression score: ", score)

concept_folder_setup_and_score('dynamic', model_type, board_name, session_name, concept_name, name, score)

Positions to consider:  29
Epoch 1/100


2024-02-19 15:47:03.843069: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 667ms/step - loss: 0.9955
Epoch 2/100
1/1 [==============================] - 0s 24ms/step - loss: 0.9935
Epoch 3/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9915
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 0.9894
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9874
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 0.9854
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9834
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9814
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 0.9794
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 0.9774
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 0.9755
Epoch 12/100
1/1 [==============================] - 0s 22ms/step - loss: 0.9735
Epoch 13/100
1/1 [==============================] - 0s 24ms/

In [28]:
epochs_to_look_at = agents_to_sample

for epoch in epochs_to_look_at:
    path = full_model_path + model_name + "_" + str(epoch) + ".keras"
    if resnet:
        model = ResNet(board_size, path)
    else:
        model = ConvNet(board_size, path)

    # Will have a length equal to the sum of the numer of rows in the positive and negative cases arrays
    # And will contain 1s for positive cases and 0s for negative cases
    # Is used as labels/targets for the regression
    all_cases = np.concatenate([positive_cases, negative_cases])
    all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
    all_labels = np.array(all_labels)
    shuffled_indices = np.arange(all_labels.shape[0])

    np.random.shuffle(shuffled_indices)

    all_cases = all_cases[shuffled_indices]
    all_labels = all_labels[shuffled_indices]

    concept_presences = {}
    
    outputs = model.get_all_activation_values(all_cases)

    # Merge outputs
    merged_outputs = []
    for output_batch in outputs:
        for i, output_layer in enumerate(output_batch):
            if len(merged_outputs) <= i:
                merged_outputs.append([])
            merged_outputs[i].extend(output_layer)

    for i, layer_output in enumerate(merged_outputs):
        merged_outputs[i] = np.array(merged_outputs[i])
    
    outputs = merged_outputs

    # Perform regression
    concept_presence_per_layer = []
    for (i, output) in enumerate(outputs):
        points = output.reshape((output.shape[0], np.prod(output.shape[1:])))
        # So one has (n, k) samples where n is the number of positions, and k is the total number of activation values in layer i.
        print(f"Performing regression for layer {i}")
        score = linear_regression.perform_regression(
            points=points[:POSITIONS_TO_CONSIDER], 
            targets=all_labels[:POSITIONS_TO_CONSIDER], 
            validation_points=points[POSITIONS_TO_CONSIDER:], 
            validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
            is_binary=BINARY,
            epochs=epochs,
            dynamic=True
        )
        score = 0 if score < 0 else score
        concept_presence_per_layer.append(score)

        print(f"The presence of {concept_name} in resblock {i} is {score}")
    
    concept_presences[concept_name] = concept_presence_per_layer

    concept_folder_setup_and_score('dynamic', model_type, board_name, session_name, concept_name, epoch, concept_presence_per_layer)

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 30.67it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:51:05.227003: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 811ms/step - loss: 1.2831
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 1.2803
Epoch 3/100
1/1 [==============================] - 0s 56ms/step - loss: 1.2774
Epoch 4/100
1/1 [==============================] - 0s 41ms/step - loss: 1.2746
Epoch 5/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2718
Epoch 6/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2691
Epoch 7/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2663
Epoch 8/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2636
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2609
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2582
Epoch 11/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2556
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2529
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:51:08.788904: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 727ms/step - loss: 1.2832
Epoch 2/100
1/1 [==============================] - 0s 41ms/step - loss: 1.2806
Epoch 3/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2781
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2756
Epoch 5/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2731
Epoch 6/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2706
Epoch 7/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2682
Epoch 8/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2657
Epoch 9/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2633
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2608
Epoch 11/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2584
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2560
Epoch 13/100
1/1 [==============================] - 0s 57ms/

2024-02-19 15:51:12.294779: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 790ms/step - loss: 1.2690
Epoch 2/100
1/1 [==============================] - 0s 68ms/step - loss: 1.2660
Epoch 3/100
1/1 [==============================] - 0s 86ms/step - loss: 1.2631
Epoch 4/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2603
Epoch 5/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2574
Epoch 6/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2547
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 1.2519
Epoch 8/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2492
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2466
Epoch 10/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2439
Epoch 11/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2413
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2388
Epoch 13/100
1/1 [==============================] - 0s 33ms/

2024-02-19 15:51:17.986706: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 3s 3s/step - loss: 1.2607
Epoch 2/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2581
Epoch 3/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2555
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2530
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2504
Epoch 6/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2479
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2454
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2429
Epoch 9/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2404
Epoch 10/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2380
Epoch 11/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2355
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2331
Epoch 13/100
1/1 [==============================] - 0s 30ms/ste

2024-02-19 15:51:21.481429: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 629ms/step - loss: 1.2551
Epoch 2/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2524
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2498
Epoch 4/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2473
Epoch 5/100
1/1 [==============================] - 0s 30ms/step - loss: 1.2448
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2423
Epoch 7/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2398
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2373
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2349
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2325
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2302
Epoch 12/100
1/1 [==============================] - 0s 44ms/step - loss: 1.2278
Epoch 13/100
1/1 [==============================] - 0s 29ms/

2024-02-19 15:51:24.834371: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 665ms/step - loss: 1.2556
Epoch 2/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2530
Epoch 3/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2505
Epoch 4/100
1/1 [==============================] - 0s 79ms/step - loss: 1.2479
Epoch 5/100
1/1 [==============================] - 0s 42ms/step - loss: 1.2454
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2429
Epoch 7/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2404
Epoch 8/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2380
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2355
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2331
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2307
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2282
Epoch 13/100
1/1 [==============================] - 0s 22ms/

2024-02-19 15:51:28.281058: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 776ms/step - loss: 1.2375
Epoch 2/100
1/1 [==============================] - 0s 48ms/step - loss: 1.2340
Epoch 3/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2306
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2273
Epoch 5/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2242
Epoch 6/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2213
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2185
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2158
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2132
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2108
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2084
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2061
Epoch 13/100
1/1 [==============================] - 0s 31ms/

2024-02-19 15:51:31.840672: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 692ms/step - loss: 0.7667
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 0.7666
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 0.7666
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 0.7665
Epoch 5/100
1/1 [==============================] - 0s 39ms/step - loss: 0.7665
Epoch 6/100
1/1 [==============================] - 0s 38ms/step - loss: 0.7664
Epoch 7/100
1/1 [==============================] - 0s 39ms/step - loss: 0.7664
Epoch 8/100
1/1 [==============================] - 0s 38ms/step - loss: 0.7663
Epoch 9/100
1/1 [==============================] - 0s 27ms/step - loss: 0.7663
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 0.7662
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 0.7662
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 0.7661
Epoch 13/100
1/1 [==============================] - 0s 23ms/

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 32.58it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:51:35.717710: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 646ms/step - loss: 1.2479
Epoch 2/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2456
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2433
Epoch 4/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2409
Epoch 5/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2386
Epoch 6/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2363
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2340
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2318
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2295
Epoch 10/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2272
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2250
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2227
Epoch 13/100
1/1 [==============================] - 0s 32ms/

2024-02-19 15:51:39.212012: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 702ms/step - loss: 1.2518
Epoch 2/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2484
Epoch 3/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2451
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2418
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2386
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2355
Epoch 7/100
1/1 [==============================] - 0s 48ms/step - loss: 1.2325
Epoch 8/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2295
Epoch 9/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2266
Epoch 10/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2237
Epoch 11/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2209
Epoch 12/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2181
Epoch 13/100
1/1 [==============================] - 0s 32ms/

2024-02-19 15:51:42.588406: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 638ms/step - loss: 1.2833
Epoch 2/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2784
Epoch 3/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2737
Epoch 4/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2691
Epoch 5/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2646
Epoch 6/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2603
Epoch 7/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2560
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2519
Epoch 9/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2479
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2440
Epoch 11/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2403
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2366
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-19 15:51:45.866413: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 649ms/step - loss: 1.3846
Epoch 2/100
1/1 [==============================] - 0s 59ms/step - loss: 1.3702
Epoch 3/100
1/1 [==============================] - 0s 38ms/step - loss: 1.3564
Epoch 4/100
1/1 [==============================] - 0s 37ms/step - loss: 1.3432
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3307
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 1.3188
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3076
Epoch 8/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2971
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2872
Epoch 10/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2780
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2695
Epoch 12/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2616
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:51:49.237075: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 646ms/step - loss: 1.2730
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2689
Epoch 3/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2650
Epoch 4/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2615
Epoch 5/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2583
Epoch 6/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2553
Epoch 7/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2525
Epoch 8/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2499
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2475
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2451
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2429
Epoch 12/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2406
Epoch 13/100
1/1 [==============================] - 0s 28ms/

2024-02-19 15:51:52.778018: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 709ms/step - loss: 1.2966
Epoch 2/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2895
Epoch 3/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2833
Epoch 4/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2780
Epoch 5/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2736
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2700
Epoch 7/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2670
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2647
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2627
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2610
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2595
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2580
Epoch 13/100
1/1 [==============================] - 0s 22ms/

2024-02-19 15:51:56.218972: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 650ms/step - loss: 1.3172
Epoch 2/100
1/1 [==============================] - 0s 64ms/step - loss: 1.3126
Epoch 3/100
1/1 [==============================] - 0s 49ms/step - loss: 1.3082
Epoch 4/100
1/1 [==============================] - 0s 42ms/step - loss: 1.3038
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2995
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2953
Epoch 7/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2912
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2872
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2832
Epoch 10/100
1/1 [==============================] - 0s 37ms/step - loss: 1.2794
Epoch 11/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2756
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2719
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:51:59.764104: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 707ms/step - loss: 0.8747
Epoch 2/100
1/1 [==============================] - 0s 42ms/step - loss: 0.8745
Epoch 3/100
1/1 [==============================] - 0s 40ms/step - loss: 0.8742
Epoch 4/100
1/1 [==============================] - 0s 28ms/step - loss: 0.8740
Epoch 5/100
1/1 [==============================] - 0s 26ms/step - loss: 0.8738
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 0.8735
Epoch 7/100
1/1 [==============================] - 0s 26ms/step - loss: 0.8733
Epoch 8/100
1/1 [==============================] - 0s 27ms/step - loss: 0.8730
Epoch 9/100
1/1 [==============================] - 0s 36ms/step - loss: 0.8728
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 0.8726
Epoch 11/100
1/1 [==============================] - 0s 39ms/step - loss: 0.8723
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 0.8721
Epoch 13/100
1/1 [==============================] - 0s 28ms/

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 29.95it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:52:03.741779: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 702ms/step - loss: 1.2717
Epoch 2/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2689
Epoch 3/100
1/1 [==============================] - 0s 45ms/step - loss: 1.2661
Epoch 4/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2634
Epoch 5/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2607
Epoch 6/100
1/1 [==============================] - 0s 54ms/step - loss: 1.2581
Epoch 7/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2555
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2529
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2504
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2479
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2454
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2430
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:52:07.274200: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 707ms/step - loss: 1.6641
Epoch 2/100
1/1 [==============================] - 0s 32ms/step - loss: 1.6224
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.5826
Epoch 4/100
1/1 [==============================] - 0s 38ms/step - loss: 1.5447
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.5090
Epoch 6/100
1/1 [==============================] - 0s 40ms/step - loss: 1.4754
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 1.4441
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.4151
Epoch 9/100
1/1 [==============================] - 0s 36ms/step - loss: 1.3885
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3643
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3424
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.3230
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:52:10.801048: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 736ms/step - loss: 1.5881
Epoch 2/100
1/1 [==============================] - 0s 39ms/step - loss: 1.5493
Epoch 3/100
1/1 [==============================] - 0s 37ms/step - loss: 1.5125
Epoch 4/100
1/1 [==============================] - 0s 27ms/step - loss: 1.4777
Epoch 5/100
1/1 [==============================] - 0s 34ms/step - loss: 1.4452
Epoch 6/100
1/1 [==============================] - 0s 37ms/step - loss: 1.4149
Epoch 7/100
1/1 [==============================] - 0s 28ms/step - loss: 1.3869
Epoch 8/100
1/1 [==============================] - 0s 32ms/step - loss: 1.3612
Epoch 9/100
1/1 [==============================] - 0s 33ms/step - loss: 1.3379
Epoch 10/100
1/1 [==============================] - 0s 31ms/step - loss: 1.3169
Epoch 11/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2980
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2814
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:52:14.331027: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 645ms/step - loss: 1.3219
Epoch 2/100
1/1 [==============================] - 0s 54ms/step - loss: 1.3128
Epoch 3/100
1/1 [==============================] - 0s 27ms/step - loss: 1.3042
Epoch 4/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2961
Epoch 5/100
1/1 [==============================] - 0s 45ms/step - loss: 1.2882
Epoch 6/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2806
Epoch 7/100
1/1 [==============================] - 0s 30ms/step - loss: 1.2731
Epoch 8/100
1/1 [==============================] - 0s 39ms/step - loss: 1.2657
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2584
Epoch 10/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2511
Epoch 11/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2439
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2368
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:52:17.802292: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 673ms/step - loss: 1.2807
Epoch 2/100
1/1 [==============================] - 0s 43ms/step - loss: 1.2704
Epoch 3/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2607
Epoch 4/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2516
Epoch 5/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2431
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2350
Epoch 7/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2275
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2203
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2134
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2068
Epoch 11/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2005
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1943
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:52:21.286005: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 680ms/step - loss: 1.4989
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 1.4597
Epoch 3/100
1/1 [==============================] - 0s 25ms/step - loss: 1.4232
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 1.3895
Epoch 5/100
1/1 [==============================] - 0s 37ms/step - loss: 1.3587
Epoch 6/100
1/1 [==============================] - 0s 39ms/step - loss: 1.3309
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.3060
Epoch 8/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2842
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2652
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2490
Epoch 11/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2355
Epoch 12/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2243
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:52:24.669679: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 689ms/step - loss: 1.2675
Epoch 2/100
1/1 [==============================] - 0s 45ms/step - loss: 1.2617
Epoch 3/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2560
Epoch 4/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2503
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2447
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2391
Epoch 7/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2336
Epoch 8/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2281
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2226
Epoch 10/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2172
Epoch 11/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2119
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2066
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-19 15:52:28.146340: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 663ms/step - loss: 0.8796
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8790
Epoch 3/100
1/1 [==============================] - 0s 28ms/step - loss: 0.8784
Epoch 4/100
1/1 [==============================] - 0s 41ms/step - loss: 0.8777
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 0.8771
Epoch 6/100
1/1 [==============================] - 0s 29ms/step - loss: 0.8765
Epoch 7/100
1/1 [==============================] - 0s 45ms/step - loss: 0.8759
Epoch 8/100
1/1 [==============================] - 0s 44ms/step - loss: 0.8753
Epoch 9/100
1/1 [==============================] - 0s 28ms/step - loss: 0.8746
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 0.8740
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 0.8734
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 0.8728
Epoch 13/100
1/1 [==============================] - 0s 24ms/

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 30.46it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:52:33.761296: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 2s 2s/step - loss: 1.2582
Epoch 2/100
1/1 [==============================] - 0s 43ms/step - loss: 1.2532
Epoch 3/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2486
Epoch 4/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2443
Epoch 5/100
1/1 [==============================] - 0s 44ms/step - loss: 1.2403
Epoch 6/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2367
Epoch 7/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2332
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2300
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2270
Epoch 10/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2241
Epoch 11/100
1/1 [==============================] - 0s 30ms/step - loss: 1.2213
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2186
Epoch 13/100
1/1 [==============================] - 0s 35ms/ste

2024-02-19 15:52:37.184360: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 673ms/step - loss: 1.4219
Epoch 2/100
1/1 [==============================] - 0s 53ms/step - loss: 1.3894
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.3597
Epoch 4/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3328
Epoch 5/100
1/1 [==============================] - 0s 38ms/step - loss: 1.3088
Epoch 6/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2875
Epoch 7/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2690
Epoch 8/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2528
Epoch 9/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2389
Epoch 10/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2268
Epoch 11/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2163
Epoch 12/100
1/1 [==============================] - 0s 33ms/step - loss: 1.2070
Epoch 13/100
1/1 [==============================] - 0s 34ms/

2024-02-19 15:52:40.799549: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 726ms/step - loss: 1.7267
Epoch 2/100
1/1 [==============================] - 0s 51ms/step - loss: 1.6601
Epoch 3/100
1/1 [==============================] - 0s 28ms/step - loss: 1.5986
Epoch 4/100
1/1 [==============================] - 0s 30ms/step - loss: 1.5427
Epoch 5/100
1/1 [==============================] - 0s 47ms/step - loss: 1.4926
Epoch 6/100
1/1 [==============================] - 0s 37ms/step - loss: 1.4486
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.4107
Epoch 8/100
1/1 [==============================] - 0s 31ms/step - loss: 1.3788
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3526
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.3317
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.3154
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3030
Epoch 13/100
1/1 [==============================] - 0s 27ms/

2024-02-19 15:52:44.374395: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 687ms/step - loss: 1.5903
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 1.5692
Epoch 3/100
1/1 [==============================] - 0s 36ms/step - loss: 1.5501
Epoch 4/100
1/1 [==============================] - 0s 35ms/step - loss: 1.5325
Epoch 5/100
1/1 [==============================] - 0s 34ms/step - loss: 1.5158
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4998
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.4842
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4689
Epoch 9/100
1/1 [==============================] - 0s 27ms/step - loss: 1.4538
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4388
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.4240
Epoch 12/100
1/1 [==============================] - 0s 27ms/step - loss: 1.4095
Epoch 13/100
1/1 [==============================] - 0s 40ms/

2024-02-19 15:52:47.729575: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 655ms/step - loss: 1.3762
Epoch 2/100
1/1 [==============================] - 0s 54ms/step - loss: 1.3408
Epoch 3/100
1/1 [==============================] - 0s 47ms/step - loss: 1.3093
Epoch 4/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2818
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2583
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2385
Epoch 7/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2220
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2083
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1967
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1867
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1776
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1689
Epoch 13/100
1/1 [==============================] - 0s 29ms/

2024-02-19 15:52:51.112681: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 673ms/step - loss: 1.4349
Epoch 2/100
1/1 [==============================] - 0s 59ms/step - loss: 1.3924
Epoch 3/100
1/1 [==============================] - 0s 49ms/step - loss: 1.3554
Epoch 4/100
1/1 [==============================] - 0s 63ms/step - loss: 1.3237
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2970
Epoch 6/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2749
Epoch 7/100
1/1 [==============================] - 0s 32ms/step - loss: 1.2567
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2418
Epoch 9/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2295
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2189
Epoch 11/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2095
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2008
Epoch 13/100
1/1 [==============================] - 0s 30ms/

2024-02-19 15:52:54.626310: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 686ms/step - loss: 1.2969
Epoch 2/100
1/1 [==============================] - 0s 40ms/step - loss: 1.2913
Epoch 3/100
1/1 [==============================] - 0s 55ms/step - loss: 1.2857
Epoch 4/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2803
Epoch 5/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2748
Epoch 6/100
1/1 [==============================] - 0s 34ms/step - loss: 1.2694
Epoch 7/100
1/1 [==============================] - 0s 22ms/step - loss: 1.2640
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2587
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2534
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 1.2481
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2429
Epoch 12/100
1/1 [==============================] - 0s 30ms/step - loss: 1.2378
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-19 15:52:58.156759: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 718ms/step - loss: 1.5301
Epoch 2/100
1/1 [==============================] - 0s 43ms/step - loss: 1.5291
Epoch 3/100
1/1 [==============================] - 0s 46ms/step - loss: 1.5281
Epoch 4/100
1/1 [==============================] - 0s 31ms/step - loss: 1.5271
Epoch 5/100
1/1 [==============================] - 0s 42ms/step - loss: 1.5262
Epoch 6/100
1/1 [==============================] - 0s 49ms/step - loss: 1.5252
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.5242
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.5233
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 1.5223
Epoch 10/100
1/1 [==============================] - 0s 37ms/step - loss: 1.5213
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.5204
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.5194
Epoch 13/100
1/1 [==============================] - 0s 26ms/

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 32.51it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:53:02.305484: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 710ms/step - loss: 1.3614
Epoch 2/100
1/1 [==============================] - 0s 52ms/step - loss: 1.3484
Epoch 3/100
1/1 [==============================] - 0s 40ms/step - loss: 1.3366
Epoch 4/100
1/1 [==============================] - 0s 39ms/step - loss: 1.3261
Epoch 5/100
1/1 [==============================] - 0s 26ms/step - loss: 1.3167
Epoch 6/100
1/1 [==============================] - 0s 27ms/step - loss: 1.3086
Epoch 7/100
1/1 [==============================] - 0s 28ms/step - loss: 1.3014
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2953
Epoch 9/100
1/1 [==============================] - 0s 28ms/step - loss: 1.2900
Epoch 10/100
1/1 [==============================] - 0s 64ms/step - loss: 1.2855
Epoch 11/100
1/1 [==============================] - 0s 70ms/step - loss: 1.2816
Epoch 12/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2781
Epoch 13/100
1/1 [==============================] - 0s 26ms/

2024-02-19 15:53:05.946462: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 811ms/step - loss: 2.5649
Epoch 2/100
1/1 [==============================] - 0s 63ms/step - loss: 2.4822
Epoch 3/100
1/1 [==============================] - 0s 30ms/step - loss: 2.4015
Epoch 4/100
1/1 [==============================] - 0s 45ms/step - loss: 2.3229
Epoch 5/100
1/1 [==============================] - 0s 27ms/step - loss: 2.2468
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 2.1736
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 2.1034
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 2.0364
Epoch 9/100
1/1 [==============================] - 0s 38ms/step - loss: 1.9727
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 1.9124
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.8553
Epoch 12/100
1/1 [==============================] - 0s 27ms/step - loss: 1.8011
Epoch 13/100
1/1 [==============================] - 0s 31ms/

2024-02-19 15:53:09.897209: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 996ms/step - loss: 1.5406
Epoch 2/100
1/1 [==============================] - 0s 49ms/step - loss: 1.5005
Epoch 3/100
1/1 [==============================] - 0s 47ms/step - loss: 1.4639
Epoch 4/100
1/1 [==============================] - 0s 29ms/step - loss: 1.4304
Epoch 5/100
1/1 [==============================] - 0s 39ms/step - loss: 1.3993
Epoch 6/100
1/1 [==============================] - 0s 26ms/step - loss: 1.3703
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3429
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.3170
Epoch 9/100
1/1 [==============================] - 0s 44ms/step - loss: 1.2924
Epoch 10/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2691
Epoch 11/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2469
Epoch 12/100
1/1 [==============================] - 0s 31ms/step - loss: 1.2260
Epoch 13/100
1/1 [==============================] - 0s 37ms/

2024-02-19 15:53:13.714996: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 730ms/step - loss: 1.3246
Epoch 2/100
1/1 [==============================] - 0s 43ms/step - loss: 1.3065
Epoch 3/100
1/1 [==============================] - 0s 45ms/step - loss: 1.2917
Epoch 4/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2785
Epoch 5/100
1/1 [==============================] - 0s 36ms/step - loss: 1.2659
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2535
Epoch 7/100
1/1 [==============================] - 0s 29ms/step - loss: 1.2409
Epoch 8/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2285
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2163
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2044
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1930
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1820
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:53:17.328509: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 797ms/step - loss: 1.7633
Epoch 2/100
1/1 [==============================] - 0s 42ms/step - loss: 1.7262
Epoch 3/100
1/1 [==============================] - 0s 44ms/step - loss: 1.6902
Epoch 4/100
1/1 [==============================] - 0s 22ms/step - loss: 1.6553
Epoch 5/100
1/1 [==============================] - 0s 30ms/step - loss: 1.6217
Epoch 6/100
1/1 [==============================] - 0s 49ms/step - loss: 1.5894
Epoch 7/100
1/1 [==============================] - 0s 42ms/step - loss: 1.5584
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.5286
Epoch 9/100
1/1 [==============================] - 0s 25ms/step - loss: 1.5003
Epoch 10/100
1/1 [==============================] - 0s 37ms/step - loss: 1.4732
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.4476
Epoch 12/100
1/1 [==============================] - 0s 27ms/step - loss: 1.4234
Epoch 13/100
1/1 [==============================] - 0s 22ms/

2024-02-19 15:53:20.812658: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 705ms/step - loss: 1.8395
Epoch 2/100
1/1 [==============================] - 0s 46ms/step - loss: 1.7850
Epoch 3/100
1/1 [==============================] - 0s 43ms/step - loss: 1.7361
Epoch 4/100
1/1 [==============================] - 0s 27ms/step - loss: 1.6923
Epoch 5/100
1/1 [==============================] - 0s 35ms/step - loss: 1.6531
Epoch 6/100
1/1 [==============================] - 0s 44ms/step - loss: 1.6179
Epoch 7/100
1/1 [==============================] - 0s 27ms/step - loss: 1.5861
Epoch 8/100
1/1 [==============================] - 0s 24ms/step - loss: 1.5573
Epoch 9/100
1/1 [==============================] - 0s 37ms/step - loss: 1.5308
Epoch 10/100
1/1 [==============================] - 0s 27ms/step - loss: 1.5061
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4829
Epoch 12/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4607
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:53:24.262436: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 718ms/step - loss: 1.1836
Epoch 2/100
1/1 [==============================] - 0s 38ms/step - loss: 1.1787
Epoch 3/100
1/1 [==============================] - 0s 40ms/step - loss: 1.1739
Epoch 4/100
1/1 [==============================] - 0s 40ms/step - loss: 1.1691
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.1644
Epoch 6/100
1/1 [==============================] - 0s 22ms/step - loss: 1.1598
Epoch 7/100
1/1 [==============================] - 0s 34ms/step - loss: 1.1552
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.1506
Epoch 9/100
1/1 [==============================] - 0s 26ms/step - loss: 1.1461
Epoch 10/100
1/1 [==============================] - 0s 22ms/step - loss: 1.1417
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1374
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1330
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-19 15:53:27.730970: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 721ms/step - loss: 1.4142
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 1.4126
Epoch 3/100
1/1 [==============================] - 0s 30ms/step - loss: 1.4110
Epoch 4/100
1/1 [==============================] - 0s 27ms/step - loss: 1.4093
Epoch 5/100
1/1 [==============================] - 0s 29ms/step - loss: 1.4077
Epoch 6/100
1/1 [==============================] - 0s 24ms/step - loss: 1.4061
Epoch 7/100
1/1 [==============================] - 0s 40ms/step - loss: 1.4044
Epoch 8/100
1/1 [==============================] - 0s 32ms/step - loss: 1.4028
Epoch 9/100
1/1 [==============================] - 0s 28ms/step - loss: 1.4012
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3995
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3979
Epoch 12/100
1/1 [==============================] - 0s 31ms/step - loss: 1.3963
Epoch 13/100
1/1 [==============================] - 0s 38ms/

Getting activation outputs: 100%|██████████| 1/1 [00:00<00:00, 31.03it/s]

Performing regression for layer 0
Epoch 1/100



2024-02-19 15:53:31.739482: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 721ms/step - loss: 1.9831
Epoch 2/100
1/1 [==============================] - 0s 75ms/step - loss: 1.9010
Epoch 3/100
1/1 [==============================] - 0s 56ms/step - loss: 1.8301
Epoch 4/100
1/1 [==============================] - 0s 48ms/step - loss: 1.7701
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1.7198
Epoch 6/100
1/1 [==============================] - 0s 40ms/step - loss: 1.6777
Epoch 7/100
1/1 [==============================] - 0s 24ms/step - loss: 1.6425
Epoch 8/100
1/1 [==============================] - 0s 25ms/step - loss: 1.6128
Epoch 9/100
1/1 [==============================] - 0s 27ms/step - loss: 1.5875
Epoch 10/100
1/1 [==============================] - 0s 40ms/step - loss: 1.5657
Epoch 11/100
1/1 [==============================] - 0s 28ms/step - loss: 1.5465
Epoch 12/100
1/1 [==============================] - 0s 28ms/step - loss: 1.5292
Epoch 13/100
1/1 [==============================] - 0s 22ms/

2024-02-19 15:53:35.278869: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 759ms/step - loss: 3.2975
Epoch 2/100
1/1 [==============================] - 0s 49ms/step - loss: 2.9449
Epoch 3/100
1/1 [==============================] - 0s 39ms/step - loss: 2.6583
Epoch 4/100
1/1 [==============================] - 0s 36ms/step - loss: 2.4449
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 2.3023
Epoch 6/100
1/1 [==============================] - 0s 28ms/step - loss: 2.2193
Epoch 7/100
1/1 [==============================] - 0s 46ms/step - loss: 2.1805
Epoch 8/100
1/1 [==============================] - 0s 28ms/step - loss: 2.1696
Epoch 9/100
1/1 [==============================] - 0s 39ms/step - loss: 2.1721
Epoch 10/100
1/1 [==============================] - 0s 33ms/step - loss: 2.1770
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 2.1770
Epoch 12/100
1/1 [==============================] - 0s 22ms/step - loss: 2.1678
Epoch 13/100
1/1 [==============================] - 0s 24ms/

2024-02-19 15:53:38.854908: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 691ms/step - loss: 1.7696
Epoch 2/100
1/1 [==============================] - 0s 54ms/step - loss: 1.7272
Epoch 3/100
1/1 [==============================] - 0s 41ms/step - loss: 1.6869
Epoch 4/100
1/1 [==============================] - 0s 28ms/step - loss: 1.6486
Epoch 5/100
1/1 [==============================] - 0s 25ms/step - loss: 1.6123
Epoch 6/100
1/1 [==============================] - 0s 36ms/step - loss: 1.5781
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.5460
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.5158
Epoch 9/100
1/1 [==============================] - 0s 38ms/step - loss: 1.4876
Epoch 10/100
1/1 [==============================] - 0s 22ms/step - loss: 1.4612
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4366
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.4135
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:53:42.554885: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 805ms/step - loss: 2.1668
Epoch 2/100
1/1 [==============================] - 0s 41ms/step - loss: 2.0181
Epoch 3/100
1/1 [==============================] - 0s 53ms/step - loss: 1.8829
Epoch 4/100
1/1 [==============================] - 0s 28ms/step - loss: 1.7582
Epoch 5/100
1/1 [==============================] - 0s 24ms/step - loss: 1.6439
Epoch 6/100
1/1 [==============================] - 0s 44ms/step - loss: 1.5405
Epoch 7/100
1/1 [==============================] - 0s 29ms/step - loss: 1.4489
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.3697
Epoch 9/100
1/1 [==============================] - 0s 29ms/step - loss: 1.3032
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.2489
Epoch 11/100
1/1 [==============================] - 0s 35ms/step - loss: 1.2057
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.1719
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:53:46.109350: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 740ms/step - loss: 1.7289
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 1.6611
Epoch 3/100
1/1 [==============================] - 0s 49ms/step - loss: 1.6021
Epoch 4/100
1/1 [==============================] - 0s 25ms/step - loss: 1.5518
Epoch 5/100
1/1 [==============================] - 0s 27ms/step - loss: 1.5093
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4737
Epoch 7/100
1/1 [==============================] - 0s 48ms/step - loss: 1.4436
Epoch 8/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4181
Epoch 9/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3960
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3764
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 1.3585
Epoch 12/100
1/1 [==============================] - 0s 29ms/step - loss: 1.3418
Epoch 13/100
1/1 [==============================] - 0s 25ms/

2024-02-19 15:53:49.771382: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 756ms/step - loss: 2.5661
Epoch 2/100
1/1 [==============================] - 0s 63ms/step - loss: 2.4048
Epoch 3/100
1/1 [==============================] - 0s 34ms/step - loss: 2.2503
Epoch 4/100
1/1 [==============================] - 0s 43ms/step - loss: 2.1039
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 1.9671
Epoch 6/100
1/1 [==============================] - 0s 48ms/step - loss: 1.8412
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 1.7274
Epoch 8/100
1/1 [==============================] - 0s 40ms/step - loss: 1.6267
Epoch 9/100
1/1 [==============================] - 0s 23ms/step - loss: 1.5396
Epoch 10/100
1/1 [==============================] - 0s 23ms/step - loss: 1.4658
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.4047
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.3548
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:53:53.432658: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 803ms/step - loss: 1.2901
Epoch 2/100
1/1 [==============================] - 0s 44ms/step - loss: 1.2865
Epoch 3/100
1/1 [==============================] - 0s 65ms/step - loss: 1.2830
Epoch 4/100
1/1 [==============================] - 0s 43ms/step - loss: 1.2794
Epoch 5/100
1/1 [==============================] - 0s 55ms/step - loss: 1.2759
Epoch 6/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2724
Epoch 7/100
1/1 [==============================] - 0s 25ms/step - loss: 1.2689
Epoch 8/100
1/1 [==============================] - 0s 26ms/step - loss: 1.2654
Epoch 9/100
1/1 [==============================] - 0s 38ms/step - loss: 1.2620
Epoch 10/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2585
Epoch 11/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2551
Epoch 12/100
1/1 [==============================] - 0s 24ms/step - loss: 1.2517
Epoch 13/100
1/1 [==============================] - 0s 23ms/

2024-02-19 15:53:59.012277: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


1/1 [==============================] - 1s 757ms/step - loss: 0.9763
Epoch 2/100
1/1 [==============================] - 0s 45ms/step - loss: 0.9760
Epoch 3/100
1/1 [==============================] - 0s 44ms/step - loss: 0.9757
Epoch 4/100
1/1 [==============================] - 0s 42ms/step - loss: 0.9755
Epoch 5/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9752
Epoch 6/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9749
Epoch 7/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9747
Epoch 8/100
1/1 [==============================] - 0s 28ms/step - loss: 0.9744
Epoch 9/100
1/1 [==============================] - 0s 49ms/step - loss: 0.9741
Epoch 10/100
1/1 [==============================] - 0s 52ms/step - loss: 0.9739
Epoch 11/100
1/1 [==============================] - 0s 23ms/step - loss: 0.9736
Epoch 12/100
1/1 [==============================] - 0s 27ms/step - loss: 0.9733
Epoch 13/100
1/1 [==============================] - 0s 22ms/