### Notebook for concept detection in neural network

In [15]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.pardir, 'src')))

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # or any {'0', '1', '2'}

from concepts import static_concepts, linear_regression, generate_static_concept_datasets
from policy import ConvNet, ResNet
from utils import concept_folder_setup_and_score

import tensorflow as tf

# Set memory growth
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

reward_function = "zero_sum" # "concept_fn", "zero_sum" or "jem"
model_name = "net"
session_name = "probing"
board_size = 7
board_name = f'{board_size}x{board_size}'
resnet = True

model_type = "resnet" if resnet else "convnet"

agents_to_sample = [0, 10, 50, 100, 300, 500, 600, 800, 1000]

full_model_path = f"../models/saved_sessions/{model_type}/{reward_function}/board_size_{board_size}/{session_name}/"

CONCEPT_FUNC = static_concepts.ko

CONCEPT_NAME = static_concepts.ko.__name__

BINARY = True

CASES_TO_SAMPLE = 25 # 25000

SAMPLE_RATIO = 0.5

# Load the models
def load_model(full_name, model_name, epoch):
    model_path = full_name + model_name + "_" + str(epoch) + ".keras"
    if resnet:
        model = ResNet(board_size, model_path)
    else:
        model = ConvNet(board_size, model_path)
    return model

agents = [load_model(full_model_path, model_name, epoch) for epoch in agents_to_sample]

In [3]:
positive_cases, negative_cases = generate_static_concept_datasets(CASES_TO_SAMPLE, agents, board_size, CONCEPT_FUNC, sample_ratio=SAMPLE_RATIO, binary=BINARY)

# Create numpy arrays
positive_cases = np.array(positive_cases)
negative_cases = np.array(negative_cases) # Target cases if continuous

Positive cases for concept 'ko':   0%|          | 0/25 [00:00<?, ?it/s]

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [3]:
# Print shapes
print("Positive cases: ", positive_cases.shape)
print("Negative cases: ", negative_cases.shape)

Positive cases:  (2500, 5, 7, 7)
Negative cases:  (2500, 5, 7, 7)


In [6]:
if not BINARY:
    print("Continuous case - skipping duplicates check")
else:
    # Test if there are any duplicates accross the two sets
    for i in range(len(positive_cases)):
        for j in range(len(negative_cases)):
            if np.array_equal(positive_cases[i], negative_cases[j]):
                print("Duplicate found!")
                print(positive_cases[i])
                print(negative_cases[j])
                break

In [4]:
if not BINARY:
    print("Continuous case - skipping duplicates check")
else:
    # Find the number of any duplicates within the positive cases
    duplicate_count = 0
    for i in range(len(positive_cases)):
        for j in range(i + 1, len(positive_cases)):
            if np.array_equal(positive_cases[i], positive_cases[j]):
                duplicate_count += 1
                break

    print("Duplicate count in positive cases: ", duplicate_count)

    # Find the number of any duplicates within the negative cases
    duplicate_count = 0
    for i in range(len(negative_cases)):
        for j in range(i + 1, len(negative_cases)):
            if np.array_equal(negative_cases[i], negative_cases[j]):
                duplicate_count += 1
                break

    print("Duplicate count in negative: ", duplicate_count)

Duplicate count in positive cases:  0
Duplicate count in negative:  36


In [4]:
from env import gogame
# Print all the positive cases
for i in range(0, 10):
    print(f"Positive case {i}:")
    print(positive_cases[i])
    print(gogame.str(positive_cases[i], nn_format=True))
    print()

Positive case 0:
[[[0. 0. 1. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]]
	0 1 2 3 4 5 6 
0	╔═╤═●═╤═╤═╤═●
1	╟─●─┼─┼─┼─┼─╢
2	╟─┼─┼─┼─┼─┼─○
3	╟─┼─┼─┼─┼─┼─╢
4	╟─┼─┼─┼─┼─┼─╢
5	

In [11]:
from env import gogame

if not BINARY:
    # Print random cases from the negative cases
    for i in range(100, 120):
        print(negative_cases[i])
        print(f'Target: {negative_cases[i]}')
        print(gogame.str(negative_cases[i], nn_format=True))
        print()

[[[1. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 1. 1.]
  [0. 0. 1. 1. 0. 1. 1.]
  [1. 0. 1. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1. 0. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[1. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 1. 1.]
  [0. 0. 0. 1. 0. 1. 1.]
  [1. 0. 1. 1. 1. 1. 1.]
  [0. 1. 1. 1. 1. 0. 1.]
  [1. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]
Target: 29.0
	0 1 2 3 4 5 6 
0	○═╤═╤═╤═╤═●═○
1	○─┼─┼─┼─●─●─╢
2	╟─┼─┼─○─┼─○─○
3	╟─┼─○─○─┼─○─○
4	○─●─○─○─○─○─○
5	╟─○─

In [5]:
# Positions to consider are 80% of the total positions
if BINARY:
    POSITIONS_TO_CONSIDER = int(0.8 * positive_cases.shape[0] * 2)
    print(f"Positions to consider: {POSITIONS_TO_CONSIDER}")
    #POSITIONS_TO_CONSIDER = 4000 #40000
    VALIDATION_POSITIONS = 10000 #10000
else:
    POSITIONS_TO_CONSIDER = int(0.8 * positive_cases.shape[0])
    print(f"Positions to consider: {POSITIONS_TO_CONSIDER}")
    #POSITIONS_TO_CONSIDER = 4000 #40000
    VALIDATION_POSITIONS = 10000

epochs = 5

Positions to consider: 4000


In [6]:
# First test if the concept can be regressed form the inputs
name = "input"
if BINARY:
    all_cases = np.concatenate([positive_cases, negative_cases])
    all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
else:
    all_cases = np.array(positive_cases)
    all_labels = negative_cases

all_labels = np.array(all_labels)
shuffled_indices = np.arange(all_labels.shape[0])

np.random.shuffle(shuffled_indices)

all_cases = all_cases[shuffled_indices]
all_labels = all_labels[shuffled_indices]

points = all_cases.reshape(all_cases.shape[0], -1)

# Use the regression
score = linear_regression.perform_regression(
    points=points[:POSITIONS_TO_CONSIDER], 
    targets=all_labels[:POSITIONS_TO_CONSIDER], 
    validation_points=points[POSITIONS_TO_CONSIDER:], 
    validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
    is_binary=BINARY,
    epochs=epochs,
    verbose=1
)

score = 0 if score < 0 else score

print("Regression score: ", score)

concept_folder_setup_and_score('static', model_type, board_name, session_name, CONCEPT_NAME, name, score)

Epoch 1/5


2024-05-06 10:58:33.097119: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 20ms/step - loss: 0.9613 - val_loss: 0.9317
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8972 - val_loss: 0.8774
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8549 - val_loss: 0.8418
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8256 - val_loss: 0.8165
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.26449999999999996
32/32 [==============================] - 0s 3ms/step
Regression score:  0.268


In [7]:
from tqdm import tqdm
epochs_to_look_at = agents_to_sample

bar = tqdm(total=len(epochs_to_look_at), desc="Epochs")

for epoch in epochs_to_look_at:
    path = full_model_path + model_name + "_" + str(epoch) + ".keras"
    if resnet:
        model = ResNet(board_size, path)
    else:
        model = ConvNet(board_size, path)

    # Will have a length equal to the sum of the numer of rows in the positive and negative cases arrays
    # And will contain 1s for positive cases and 0s for negative cases
    # Is used as labels/targets for the regression
    if BINARY:
        all_cases = np.concatenate([positive_cases, negative_cases])
        all_labels = [1] * positive_cases.shape[0] + [0] * negative_cases.shape[0]
    else:
        all_cases = np.array(positive_cases)
        all_labels = negative_cases

    all_labels = np.array(all_labels)
    shuffled_indices = np.arange(all_labels.shape[0])

    np.random.shuffle(shuffled_indices)

    all_cases = all_cases[shuffled_indices]
    all_labels = all_labels[shuffled_indices]

    concept_presences = {}
    
    outputs = model.get_all_activation_values(all_cases)

    # Merge outputs
    merged_outputs = []
    for output_batch in outputs:
        for i, output_layer in enumerate(output_batch):
            if len(merged_outputs) <= i:
                merged_outputs.append([])
            merged_outputs[i].extend(output_layer)

    for i, layer_output in enumerate(merged_outputs):
        merged_outputs[i] = np.array(merged_outputs[i])
    
    outputs = merged_outputs

    # Perform regression
    concept_presence_per_layer = []
    for (i, output) in enumerate(outputs):
        points = output.reshape((output.shape[0], np.prod(output.shape[1:])))
        # So one has (n, k) samples where n is the number of positions, and k is the total number of activation values in layer i.
        print(f"Performing regression for layer {i}")
        score = linear_regression.perform_regression(
            points=points[:POSITIONS_TO_CONSIDER], 
            targets=all_labels[:POSITIONS_TO_CONSIDER], 
            validation_points=points[POSITIONS_TO_CONSIDER:], 
            validation_targets=all_labels[POSITIONS_TO_CONSIDER:], 
            is_binary=BINARY,
            epochs=epochs,
            verbose=1
        )
        score = 0 if score < 0 else score
        concept_presence_per_layer.append(score)

        print(f"The presence of {CONCEPT_NAME} in resblock {i} is {score}")
        
    concept_presences[CONCEPT_NAME] = concept_presence_per_layer

    concept_folder_setup_and_score('static', model_type, board_name, session_name, CONCEPT_NAME, epoch, concept_presence_per_layer)

    bar.update()

Getting activation outputs: 100%|██████████| 157/157 [00:05<00:00, 30.45it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 10:58:55.429648: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 23ms/step - loss: 1.2974 - val_loss: 1.1061
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 0.9730 - val_loss: 0.8498
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7797 - val_loss: 0.7189
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7044 - val_loss: 0.6891
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.30800000000000005
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.30200000000000005
Performing regression for layer 1
Epoch 1/5


2024-05-06 10:59:08.103494: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3076 - val_loss: 1.1067
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9599 - val_loss: 0.8329
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7604 - val_loss: 0.7098
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7005 - val_loss: 0.6950
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.06549999999999989
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.05800000000000005
Performing regression for layer 2
Epoch 1/5


2024-05-06 10:59:19.990911: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.2981 - val_loss: 1.1182
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9886 - val_loss: 0.8674
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7965 - val_loss: 0.7329
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7138 - val_loss: 0.6953
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.30699999999999994
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.30000000000000004
Performing regression for layer 3
Epoch 1/5


2024-05-06 10:59:31.973132: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3004 - val_loss: 1.1053
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9636 - val_loss: 0.8405
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7677 - val_loss: 0.7160
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7039 - val_loss: 0.6965
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.129
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.1180000000000001
Performing regression for layer 4
Epoch 1/5


2024-05-06 10:59:43.811728: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3209 - val_loss: 1.1495
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0244 - val_loss: 0.9031
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8298 - val_loss: 0.7612
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7372 - val_loss: 0.7104
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.30600000000000005
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.30400000000000005
Performing regression for layer 5
Epoch 1/5


2024-05-06 10:59:56.043228: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3115 - val_loss: 1.1269
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9895 - val_loss: 0.8672
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7944 - val_loss: 0.7366
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7184 - val_loss: 0.7042
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.10299999999999998
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.08200000000000007
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:00:07.951881: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 0.7807 - val_loss: 0.7722
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 0.7738 - val_loss: 0.7655
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7678 - val_loss: 0.7598
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7626 - val_loss: 0.7551
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
-0.011499999999999955
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.02400000000000002
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:00:20.192445: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 0.7994 - val_loss: 0.7996
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7932 - val_loss: 0.7935
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7873 - val_loss: 0.7875
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7818 - val_loss: 0.7818
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.08549999999999991
32/32 [==============================] - 0s 3ms/step


Epochs:  11%|█         | 1/9 [01:43<13:47, 103.41s/it]

The presence of atari in resblock 7 is 0.10000000000000009


Getting activation outputs: 100%|██████████| 157/157 [00:04<00:00, 32.43it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:00:40.097970: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 5s 21ms/step - loss: 1.3131 - val_loss: 1.1384
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9980 - val_loss: 0.8851
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8009 - val_loss: 0.7431
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7112 - val_loss: 0.6983
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.31899999999999995
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.272
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:00:52.710273: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3213 - val_loss: 1.1411
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9960 - val_loss: 0.8799
Epoch 3/5
125/125 [==============================] - 2s 19ms/step - loss: 0.7969 - val_loss: 0.7416
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7139 - val_loss: 0.7027
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.30400000000000005
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.246
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:01:05.198019: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3480 - val_loss: 1.1808
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0460 - val_loss: 0.9324
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8431 - val_loss: 0.7794
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7380 - val_loss: 0.7162
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.32099999999999995
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.276
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:01:17.584244: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3039 - val_loss: 1.1291
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9937 - val_loss: 0.8832
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8019 - val_loss: 0.7471
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7196 - val_loss: 0.7077
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.2509999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.18999999999999995
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:01:29.588662: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3521 - val_loss: 1.2075
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0801 - val_loss: 0.9759
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8901 - val_loss: 0.8307
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7793 - val_loss: 0.7501
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.3340000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.28
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:01:41.595699: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3035 - val_loss: 1.1370
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0068 - val_loss: 0.8982
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8208 - val_loss: 0.7654
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7361 - val_loss: 0.7186
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.2769999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.22399999999999998
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:01:53.734736: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 0.7765 - val_loss: 0.7819
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7715 - val_loss: 0.7768
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7666 - val_loss: 0.7719
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7620 - val_loss: 0.7672
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.1160000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.09600000000000009
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:02:05.623859: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 0.9101 - val_loss: 0.8605
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8415 - val_loss: 0.8114
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8007 - val_loss: 0.7848
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 0.7786 - val_loss: 0.7717
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.14850000000000008
32/32 [==============================] - 0s 3ms/step


Epochs:  22%|██▏       | 2/9 [03:28<12:12, 104.62s/it]

The presence of atari in resblock 7 is 0.12200000000000011


Getting activation outputs: 100%|██████████| 157/157 [00:05<00:00, 30.51it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:02:24.478931: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 23ms/step - loss: 1.3287 - val_loss: 1.1562
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0231 - val_loss: 0.9058
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8216 - val_loss: 0.7552
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7199 - val_loss: 0.7002
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.31600000000000006
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.29400000000000004
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:02:37.223399: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.3113 - val_loss: 1.1402
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0093 - val_loss: 0.8968
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8184 - val_loss: 0.7588
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7275 - val_loss: 0.7086
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.3005
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.256
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:02:50.264204: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3344 - val_loss: 1.1781
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 1.0565 - val_loss: 0.9447
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8628 - val_loss: 0.7954
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7544 - val_loss: 0.7261
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.3600000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.3380000000000001
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:03:02.502567: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.3245 - val_loss: 1.1488
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0115 - val_loss: 0.8904
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8111 - val_loss: 0.7505
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 0.7241 - val_loss: 0.7067
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.2875000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.29200000000000004
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:03:15.724865: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3438 - val_loss: 1.2038
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0936 - val_loss: 0.9915
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9119 - val_loss: 0.8485
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7995 - val_loss: 0.7693
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.42799999999999994
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.4099999999999999
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:03:28.357810: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 24ms/step - loss: 1.3160 - val_loss: 1.1530
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0227 - val_loss: 0.9101
Epoch 3/5
125/125 [==============================] - 2s 20ms/step - loss: 0.8298 - val_loss: 0.7694
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7362 - val_loss: 0.7165
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.45300000000000007
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.44799999999999995
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:03:43.732426: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.0000 - val_loss: 0.9700
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9522 - val_loss: 0.9256
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9113 - val_loss: 0.8882
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8775 - val_loss: 0.8573
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
-0.0024999999999999467
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:03:55.817107: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 0.8201 - val_loss: 0.8158
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 0.8107 - val_loss: 0.8070
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8019 - val_loss: 0.7988
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.7938 - val_loss: 0.7911
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.030999999999999917
32/32 [==============================] - 0s 3ms/step


Epochs:  33%|███▎      | 3/9 [05:18<10:41, 106.91s/it]

The presence of atari in resblock 7 is 0


Getting activation outputs: 100%|██████████| 157/157 [00:04<00:00, 32.14it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:04:13.694065: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3249 - val_loss: 1.1421
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0023 - val_loss: 0.8823
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8006 - val_loss: 0.7398
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7123 - val_loss: 0.6976
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.32099999999999995
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.30000000000000004
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:04:25.761797: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 19ms/step - loss: 1.3304 - val_loss: 1.1585
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0234 - val_loss: 0.9069
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8227 - val_loss: 0.7564
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 0.7196 - val_loss: 0.6970
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.4555
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.42599999999999993
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:04:38.119700: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3510 - val_loss: 1.2119
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.1043 - val_loss: 1.0052
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 0.9289 - val_loss: 0.8602
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8115 - val_loss: 0.7736
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5265
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.536
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:04:50.533162: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3781 - val_loss: 1.2599
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1619 - val_loss: 1.0698
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9969 - val_loss: 0.9298
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8803 - val_loss: 0.8370
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.53
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.524
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:05:02.763269: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3786 - val_loss: 1.2661
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1847 - val_loss: 1.1069
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0483 - val_loss: 0.9892
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9463 - val_loss: 0.9001
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5469999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.554
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:05:15.246329: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3991 - val_loss: 1.2788
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1815 - val_loss: 1.0942
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0228 - val_loss: 0.9608
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9123 - val_loss: 0.8718
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5309999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.526
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:05:27.473692: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.0048 - val_loss: 1.0025
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9728 - val_loss: 0.9752
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9555 - val_loss: 0.9585
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9427 - val_loss: 0.9453
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
-0.121
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:05:39.789525: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3956 - val_loss: 1.2245
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0615 - val_loss: 0.9586
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8857 - val_loss: 0.8457
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8254 - val_loss: 0.8135
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.012499999999999956
32/32 [==============================] - 0s 3ms/step


Epochs:  44%|████▍     | 4/9 [07:02<08:49, 105.82s/it]

The presence of atari in resblock 7 is 0.008000000000000007


Getting activation outputs: 100%|██████████| 157/157 [00:04<00:00, 32.95it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:05:57.741047: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3113 - val_loss: 1.1254
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9921 - val_loss: 0.8675
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7931 - val_loss: 0.7296
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7089 - val_loss: 0.6939
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.3055000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.32400000000000007
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:06:09.995609: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3217 - val_loss: 1.1697
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0750 - val_loss: 0.9655
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9006 - val_loss: 0.8187
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7766 - val_loss: 0.7193
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5640000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.562
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:06:22.340736: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.3814 - val_loss: 1.2345
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1515 - val_loss: 1.0586
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9996 - val_loss: 0.9233
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.8808 - val_loss: 0.8203
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5805
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.5820000000000001
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:06:36.087433: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 5s 21ms/step - loss: 1.3577 - val_loss: 1.2260
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1534 - val_loss: 1.0676
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0165 - val_loss: 0.9464
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.9038 - val_loss: 0.8483
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5785
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.5800000000000001
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:06:48.504143: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3721 - val_loss: 1.2769
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.2080 - val_loss: 1.1287
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 1.0969 - val_loss: 1.0305
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0098 - val_loss: 0.9481
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5814999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.6000000000000001
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:07:00.706680: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.4339 - val_loss: 1.3055
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.2358 - val_loss: 1.1654
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1071 - val_loss: 1.0346
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 1.0020 - val_loss: 0.9397
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.5425
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.5660000000000001
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:07:13.055763: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 3.1207 - val_loss: 2.9377
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.7473 - val_loss: 2.5692
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.3946 - val_loss: 2.2270
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 2.0731 - val_loss: 1.9208
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.06499999999999995
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.05800000000000005
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:07:25.006586: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 2.0518 - val_loss: 1.7370
Epoch 2/5
125/125 [==============================] - 2s 16ms/step - loss: 1.4936 - val_loss: 1.2536
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 1.1022 - val_loss: 0.9760
Epoch 4/5
125/125 [==============================] - 2s 16ms/step - loss: 0.9116 - val_loss: 0.8667
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.11949999999999994
32/32 [==============================] - 0s 3ms/step


Epochs:  56%|█████▌    | 5/9 [08:47<07:02, 105.57s/it]

The presence of atari in resblock 7 is 0.10400000000000009


Getting activation outputs: 100%|██████████| 157/157 [00:04<00:00, 33.15it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:07:42.846665: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3233 - val_loss: 1.1464
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0134 - val_loss: 0.8930
Epoch 3/5
125/125 [==============================] - 2s 16ms/step - loss: 0.8122 - val_loss: 0.7461
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 0.7182 - val_loss: 0.7009
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.4325000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.4179999999999999
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:07:55.068937: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.4657 - val_loss: 1.3306
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.2431 - val_loss: 1.1968
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1359 - val_loss: 1.1075
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0461 - val_loss: 1.0184
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.623
32/32 [==============================] - 0s 6ms/step
The presence of atari in resblock 1 is 0.6040000000000001
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:08:08.321490: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 22ms/step - loss: 1.3673 - val_loss: 1.2616
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 1.1917 - val_loss: 1.1587
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0914 - val_loss: 1.0662
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0069 - val_loss: 0.9886
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.637
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.6100000000000001
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:08:21.684740: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.3885 - val_loss: 1.2904
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.2117 - val_loss: 1.1811
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.1142 - val_loss: 1.1034
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 1.0289 - val_loss: 1.0173
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.623
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.558
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:08:34.832126: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.6006 - val_loss: 1.3948
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 1.3112 - val_loss: 1.2893
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.2287 - val_loss: 1.2127
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 1.1560 - val_loss: 1.1519
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.605
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 4 is 0.5680000000000001
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:08:47.742599: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 1.3993 - val_loss: 1.3171
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.2521 - val_loss: 1.2178
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 1.1635 - val_loss: 1.1464
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.0898 - val_loss: 1.0805
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.597
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.5780000000000001
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:09:00.219845: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 2.4482 - val_loss: 2.2715
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.2689 - val_loss: 2.1025
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.1154 - val_loss: 1.9584
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.9855 - val_loss: 1.8351
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
-0.030000000000000027
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:09:12.556622: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 1.5976 - val_loss: 1.4988
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.4961 - val_loss: 1.4198
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 1.4198 - val_loss: 1.3558
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.3557 - val_loss: 1.2987
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.0665
32/32 [==============================] - 0s 3ms/step


Epochs:  67%|██████▋   | 6/9 [10:35<05:19, 106.42s/it]

The presence of atari in resblock 7 is 0.06400000000000006


Getting activation outputs: 100%|██████████| 157/157 [00:06<00:00, 26.09it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:09:33.003029: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 2.3803 - val_loss: 1.8101
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 1.7447 - val_loss: 1.6627
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 1.6033 - val_loss: 1.5998
Epoch 4/5
125/125 [==============================] - 3s 20ms/step - loss: 1.5149 - val_loss: 1.5282
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6875
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 0 is 0.5940000000000001
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:09:46.466605: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 5s 39ms/step - loss: 2.9169 - val_loss: 2.2356
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.1356 - val_loss: 2.1568
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.8859 - val_loss: 1.8829
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.7211 - val_loss: 1.8225
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.673
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.5640000000000001
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:10:01.412070: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 3.2522 - val_loss: 2.4774
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.3225 - val_loss: 2.1335
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.0141 - val_loss: 2.0117
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.8604 - val_loss: 2.1527
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6319999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.5780000000000001
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:10:13.968485: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 2.6000 - val_loss: 2.2073
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.0141 - val_loss: 2.0707
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.8172 - val_loss: 1.8714
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.6565 - val_loss: 1.7859
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6735
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 3 is 0.556
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:10:26.614312: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 3.8902 - val_loss: 2.9306
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.7051 - val_loss: 2.5631
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.2863 - val_loss: 2.3095
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 2.0102 - val_loss: 2.2972
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6715
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.558
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:10:39.292921: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 3.1944 - val_loss: 2.3541
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 2.2730 - val_loss: 2.2049
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.0888 - val_loss: 1.9688
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.9049 - val_loss: 1.9241
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.5660000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.478
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:10:51.898468: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 6.5762 - val_loss: 6.1135
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 6.2423 - val_loss: 5.7893
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 5.9196 - val_loss: 5.4781
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 5.6133 - val_loss: 5.1940
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.123
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.16999999999999993
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:11:04.129481: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 4.7235 - val_loss: 4.6681
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 4.5441 - val_loss: 4.4938
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 4.3778 - val_loss: 4.3343
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 4.2195 - val_loss: 4.1810
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.17700000000000005
32/32 [==============================] - 0s 3ms/step


Epochs:  78%|███████▊  | 7/9 [12:27<03:36, 108.06s/it]

The presence of atari in resblock 7 is 0.18599999999999994


Getting activation outputs: 100%|██████████| 157/157 [00:07<00:00, 20.58it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:11:27.221892: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 22ms/step - loss: 2.4969 - val_loss: 2.1307
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 1.8707 - val_loss: 1.8765
Epoch 3/5
125/125 [==============================] - 3s 25ms/step - loss: 1.7224 - val_loss: 1.7769
Epoch 4/5
125/125 [==============================] - 2s 19ms/step - loss: 1.6085 - val_loss: 1.8453
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6875
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.5760000000000001
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:11:42.029235: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 23ms/step - loss: 3.1532 - val_loss: 2.6884
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 2.2763 - val_loss: 2.3218
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 1.9845 - val_loss: 2.1473
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 1.8267 - val_loss: 2.0248
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6924999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 1 is 0.522
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:11:55.679023: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 28ms/step - loss: 3.8926 - val_loss: 2.9788
Epoch 2/5
125/125 [==============================] - 3s 21ms/step - loss: 2.5417 - val_loss: 2.5343
Epoch 3/5
125/125 [==============================] - 3s 20ms/step - loss: 2.2118 - val_loss: 2.4115
Epoch 4/5
125/125 [==============================] - 2s 19ms/step - loss: 2.0397 - val_loss: 2.2403
Epoch 5/5
125/125 [==============================] - 1s 5ms/step
0.6519999999999999
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 2 is 0.56
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:12:11.116840: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 23ms/step - loss: 2.7322 - val_loss: 2.6197
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 2.1683 - val_loss: 2.1638
Epoch 3/5
125/125 [==============================] - 3s 20ms/step - loss: 1.9039 - val_loss: 2.3628
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.7502 - val_loss: 1.9223
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6779999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.544
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:12:24.764499: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 4.3122 - val_loss: 3.2334
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 3.0055 - val_loss: 2.9328
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 2.4926 - val_loss: 2.9365
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 2.2068 - val_loss: 2.7469
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.716
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.538
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:12:37.729363: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 22ms/step - loss: 2.9957 - val_loss: 2.7391
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 2.3304 - val_loss: 2.3475
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 2.0991 - val_loss: 2.1925
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.8848 - val_loss: 2.0436
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.552
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 5 is 0.41999999999999993
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:12:51.199283: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 4s 23ms/step - loss: 5.8518 - val_loss: 5.1439
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 5.3644 - val_loss: 4.6839
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 4.9192 - val_loss: 4.2761
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 4.5147 - val_loss: 3.9138
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.2549999999999999
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.274
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:13:04.599195: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 22ms/step - loss: 4.9232 - val_loss: 4.9473
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 4.6944 - val_loss: 4.7455
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 4.4854 - val_loss: 4.5576
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 4.2919 - val_loss: 4.3830
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.15700000000000003
32/32 [==============================] - 0s 3ms/step


Epochs:  89%|████████▉ | 8/9 [14:28<01:52, 112.22s/it]

The presence of atari in resblock 7 is 0.12400000000000011


Getting activation outputs: 100%|██████████| 157/157 [00:05<00:00, 27.75it/s]


Performing regression for layer 0
Epoch 1/5


2024-05-06 11:13:27.450010: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 22ms/step - loss: 2.8337 - val_loss: 2.1946
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 2.0721 - val_loss: 2.0058
Epoch 3/5
125/125 [==============================] - 2s 19ms/step - loss: 1.8700 - val_loss: 1.8779
Epoch 4/5
125/125 [==============================] - 2s 19ms/step - loss: 1.6935 - val_loss: 1.7690
Epoch 5/5
125/125 [==============================] - 1s 4ms/step
0.683
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 0 is 0.5800000000000001
Performing regression for layer 1
Epoch 1/5


2024-05-06 11:13:41.236729: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 3.6667 - val_loss: 2.5618
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 2.4325 - val_loss: 2.3239
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 2.1633 - val_loss: 2.1500
Epoch 4/5
125/125 [==============================] - 3s 21ms/step - loss: 1.9355 - val_loss: 2.0219
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6679999999999999
32/32 [==============================] - 0s 4ms/step
The presence of atari in resblock 1 is 0.562
Performing regression for layer 2
Epoch 1/5


2024-05-06 11:13:55.875165: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 4.0331 - val_loss: 3.2297
Epoch 2/5
125/125 [==============================] - 2s 18ms/step - loss: 2.8569 - val_loss: 2.6604
Epoch 3/5
125/125 [==============================] - 2s 19ms/step - loss: 2.5312 - val_loss: 2.4704
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 2.1655 - val_loss: 2.3176
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6515
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 2 is 0.5940000000000001
Performing regression for layer 3
Epoch 1/5


2024-05-06 11:14:09.019191: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 23ms/step - loss: 2.9523 - val_loss: 2.5612
Epoch 2/5
125/125 [==============================] - 2s 19ms/step - loss: 2.2456 - val_loss: 2.2985
Epoch 3/5
125/125 [==============================] - 2s 19ms/step - loss: 1.9382 - val_loss: 2.1156
Epoch 4/5
125/125 [==============================] - 2s 18ms/step - loss: 1.7295 - val_loss: 2.1246
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.687
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 3 is 0.496
Performing regression for layer 4
Epoch 1/5


2024-05-06 11:14:22.615166: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 21ms/step - loss: 5.2695 - val_loss: 4.4477
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 3.6316 - val_loss: 3.3402
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 2.9312 - val_loss: 3.0501
Epoch 4/5
125/125 [==============================] - 2s 19ms/step - loss: 2.4866 - val_loss: 2.8502
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.6890000000000001
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 4 is 0.54
Performing regression for layer 5
Epoch 1/5


2024-05-06 11:14:36.092469: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 22ms/step - loss: 3.0373 - val_loss: 2.5850
Epoch 2/5
125/125 [==============================] - 3s 21ms/step - loss: 2.3697 - val_loss: 2.3927
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 2.0967 - val_loss: 2.2890
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 1.8801 - val_loss: 2.1004
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.609
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 5 is 0.5
Performing regression for layer 6
Epoch 1/5


2024-05-06 11:14:49.328852: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 5.5152 - val_loss: 4.9156
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 5.1827 - val_loss: 4.6144
Epoch 3/5
125/125 [==============================] - 2s 18ms/step - loss: 4.9167 - val_loss: 4.3905
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 4.7022 - val_loss: 4.2097
Epoch 5/5
125/125 [==============================] - 0s 3ms/step
0.21300000000000008
32/32 [==============================] - 0s 3ms/step
The presence of atari in resblock 6 is 0.264
Performing regression for layer 7
Epoch 1/5


2024-05-06 11:15:01.585795: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:954] model_pruner failed: INVALID_ARGUMENT: Graph does not contain terminal node AssignAddVariableOp_2.


125/125 [==============================] - 3s 20ms/step - loss: 5.8449 - val_loss: 5.5416
Epoch 2/5
125/125 [==============================] - 2s 17ms/step - loss: 5.6323 - val_loss: 5.3477
Epoch 3/5
125/125 [==============================] - 2s 17ms/step - loss: 5.4238 - val_loss: 5.1608
Epoch 4/5
125/125 [==============================] - 2s 17ms/step - loss: 5.2230 - val_loss: 4.9774
Epoch 5/5
125/125 [==============================] - 0s 2ms/step
0.15500000000000003
32/32 [==============================] - 0s 3ms/step


Epochs: 100%|██████████| 9/9 [16:24<00:00, 113.51s/it]

The presence of atari in resblock 7 is 0.18799999999999994
